<div style="text-align: center; padding: 20px;">
<h1 align="center" style="font-size: 28px; color:rgb(156, 90, 255, 1); width: 100%;">━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>تمرین 4 - بازیابی هوشمند اطلاعات<br>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</h1>
<p style="color: #666; font-size: 16px;">طراح تمرین: امیرحسین صفدریان</p>
<p style="color: #666; font-size: 16px; margin-bottom: 30px;">safdarian2000@gmail.com</p>

<div style="border: 2px dashed rgba(156, 90, 255, 1); border-radius: 8px; padding: 20px; margin: 20px auto; max-width: 500px; text-align: right;">
<p style="color: rgba(156, 90, 255, 1); font-size: 18px; margin-bottom: 15px;"> مشخصات دانشجو:</p>
<p style="color: #666; margin: 5px;">نام و نام خانوادگی: روژین پناو</p>
<p style="color: #666; margin: 5px;">شماره دانشجویی: 220701046</p>
<p style="color: #666; margin: 5px;">تاریخ ارسال: 1404/10/4 </p>
</div>
</div>

<div dir="rtl" style="text-align: justify;  padding: 25px; background-color:rgba(60, 4, 82, 0.21); border-radius: 12px; border: 2px solidrgb(2, 34, 22);"
<div style="line-height: 2.0; font-size: 17px;">
<div style="padding-right:40px">
</div>
<br>

<div style="padding-right:100px">
 ساختار تمرین:

<b>سوال اول - استخراج WORD ASSOCIATIONها  </b>


<b>سوال دوم - کار با PRETRAINED WORD EMBEDDING </b>

<b> سوال سوم - پیاده‌سازی مدل‌های LEARNING TO RANK </b>

</div>
</div>


</div>
</div>

<div dir="rtl">
   تایید می‌کنم که از LLMها مطابق با دستورالعمل های بارگذاری شده در سامانه Elearn درس به طور مسئولانه استفاده کرده‌ام. تمام اجزای کار خود را درک می‌کنم و آماده بحث شفاهی درباره آنها هستم.
</div>


# <div style="text-align: center; direction: rtl;"><h1 align="center" style="font-size: 24px; padding: 20px;">━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>سوال اول - استخراج WORD ASSOCIATIONها <br>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</h1></div>


In [299]:
import math as _math
import os as _os
import re as _re
import zipfile as _zip
import urllib.request as _urlreq

from collections import Counter as _Counter
from collections import defaultdict as _ddict

import numpy as _np
import pandas as _pd
import requests as _requests
import xgboost as _xgb
from tqdm import tqdm as _tqdm

import matplotlib.pyplot as _plt
import plotly.express as _px
import plotly.graph_objects as _go
from plotly.subplots import make_subplots as _make_subplots

from sentence_transformers import SentenceTransformer

from sklearn.datasets import fetch_20newsgroups as _fetch_news
from sklearn.decomposition import PCA as _PCA
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS as _STOPWORDS
from sklearn.feature_extraction.text import TfidfVectorizer as _TFIDF
from sklearn.metrics.pairwise import cosine_similarity as _cos_sim
from sklearn.model_selection import train_test_split as _split
from sklearn.preprocessing import StandardScaler as _Scaler
from sklearn.svm import LinearSVC as _LSVC
import sys
from scipy.spatial import ConvexHull


## <div style="text-align: right; direction: rtl;"> مجموعه‌داده</div>


<div dir="rtl">
مجموعه‌داده‌ای که در این بخش مورد استفاده قرار گرفته، آرشیوی بزرگ از متون طبقه‌بندی‌شده است که با نام <code>20 Newsgroups</code> شناخته می‌شود. این آرشیو شامل حدود <strong>۱۸٬۸۴۶</strong> سند متنی مستقل است که هرکدام به یکی از <strong>۲۰ حوزه‌ی خبری مجزا</strong> وابسته هستند. محتوای اسناد عمدتاً از مکاتبات دیجیتال قدیمی، پیام‌های گروهی و نوشته‌های ارسال‌شده در انجمن‌های اینترنتی تشکیل شده و از منابع متنوعی جمع‌آوری شده‌اند. تمرکز اصلی این مطالعه، استخراج الگوهای متنی و نسبت‌دادن هر سند به گروه خبری متناظر آن است.

<h3>نحوه‌ی دریافت و آماده‌سازی داده‌ها</h3>

برای دریافت داده‌ها، از قابلیت‌های کتابخانه‌ی <code>scikit-learn</code> استفاده شده است. تابع <code>fetch_20newsgroups</code> داده‌ها را به‌گونه‌ای بارگذاری می‌کند که ترتیب آن‌ها تصادفی باشد. خروجی این فرآیند شامل مجموعه‌ای از متن‌ها به‌همراه شناسه‌ی عددی هر دسته‌ی خبری است. در مجموع، این مجموعه شامل <strong>۱۸٬۸۴۶</strong> نمونه می‌باشد که هر نمونه یک سند متنی و یک برچسب وابسته به آن دارد. این برچسب‌ها نقش کلیدی در فرآیند آموزش، ارزیابی و مقایسه‌ی مدل‌های یادگیری ماشین ایفا می‌کنند.

<h4>مروری سریع بر ویژگی‌های اولیه‌ی داده‌ها:</h4>

<ul>
  <li>تعداد کل اسناد متنی: ۱۸٬۸۴۶ مورد</li>
  <li>تعداد شناسه‌های دسته‌بندی: ۱۸٬۸۴۶ مقدار</li>
  <li>نمونه‌ی نخست: دارای برچسب عددی <code>10</code> که به حوزه‌ی خبری <code>rec.sport.hockey</code> اختصاص دارد.</li>
</ul>
</div>


In [330]:
def _build_removal_flags(flag):
    if not flag:
        return ()
    parts = ["headers", "footers", "quotes"]
    return tuple(p for p in parts)


def _load_dataset(removals):
    return _fetch_news(
        subset="all",
        shuffle=True,
        random_state=42,
        remove=removals if removals else None,
    )


def _emit_overview(bundle):
    total_docs = len(bundle.data)
    total_labels = len(bundle.target)

    first_idx = int(bundle.target[0])
    first_name = bundle.target_names[first_idx]
    snippet = bundle.data[0][:600]

    print("=== Dataset Overview ===")
    print(f"Total documents: {total_docs}")
    print(f"Total labels: {total_labels}")
    print(f"Initial label: [{first_idx}] corresponds to '{first_name}'")
    print("Excerpt from first document:\n")
    print(snippet)


def main():
    removal_config = _build_removal_flags(REMOVE_HEADERS_FOOTERS_QUOTES)
    dataset = _load_dataset(removal_config)
    _emit_overview(dataset)


REMOVE_HEADERS_FOOTERS_QUOTES = True
main()


=== Dataset Overview ===
Total documents: 18846
Total labels: 18846
Initial label: [10] corresponds to 'rec.sport.hockey'
Excerpt from first document:



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyw


## <div style="text-align: right; direction: rtl;">پیش‌پردازش و آماده‌سازی پیکره</div>


<div dir="rtl">

### بخش پیش‌پردازش داده‌ها و تحلیل نتایج

در این بخش متون خبری را برای استفاده در مدل‌های یادگیری ماشین آماده کردم. هدف اصلی  کاهش نویزها، استانداردسازی متن‌ها و استخراج ویژگی‌های معنادار از داده‌ها بود تا بخش‌های بعدی پروژه، مانند تحلیل embedding و مدل‌های Learning to Rank، بتوانند به درستی عمل کنند.

#### شرح پیاده‌سازی و منطق پروژه

برای پیش‌پردازش ابتدا تمام متن‌ها را با تبدیل حروف به حالت کوچک (lowercase) و حذف نویزهای غیر متنی آماده کردم. سپس با استفاده از پارامتر `segment_mode="doc"` تصمیم گرفتم که هر سند به‌عنوان یک بخش مستقل در نظر گرفته شود تا درک سطح سندی و محاسبات آماری ساده‌تر باشد.  

در مرحله توکن‌سازی، متن‌ها به کلمات جداگانه تقسیم شدند و تمامی کلمات توقف (Stopwords) حذف شد. علاوه بر این، تنها کلماتی با طول حداقل ۲ کاراکتر و با حداقل تکرار ۵ بار در مجموعه داده‌ها نگه داشته شدند. این کار باعث شد تا واژگان نهایی تنها شامل کلمات معنی‌دار و پرکاربرد باشند و نویز ناشی از کلمات کم‌اهمیت کاهش یابد.  

برای ساخت دیکشنری واژگان، تعداد تکرار هر کلمه در کل مجموعه داده محاسبه شد و کلمات با فرکانس کمتر از ۵ حذف شدند. نتیجه این مرحله یک واژگان ۲۹,۰۱۳ کلمه‌ای بود که شامل پرکاربردترین کلمات مانند `ax`, `like`, `people` و `just` می‌شود.  

#### تحلیل عمیق نتایج تجربی

نتایج اجرای پیش‌پردازش به شکل زیر به دست آمد:

| معیار | مقدار |
|-------|-------|
| تعداد بخش‌ها (Segments) | 18,294 |
| اندازه نهایی واژگان (Vocabulary Size) | 29,013 |

لیست ۳۰ کلمه پرکاربرد و تعداد تکرار آن‌ها نشان می‌دهد که واژگان غالباً شامل کلمات عمومی و پر تکرار در متون خبری هستند:

| رتبه | کلمه | تعداد تکرار |
|------|-------|-------------|
| 1 | ax | 62,401 |
| 2 | like | 6,529 |
| 3 | don | 6,526 |
| 4 | people | 6,459 |
| 5 | just | 6,178 |
| 6 | know | 5,774 |
| 7 | use | 5,030 |
| 8 | think | 5,004 |
| 9 | time | 4,879 |
| 10 | max | 4,729 |
| … | … | … |
| 30 | really | 2,397 |

مشاهده می‌شود که برخی کلمات مانند `ax` بسیار پر تکرار هستند که احتمالاً ناشی از محتواهای متنی مرتبط با ایمیل یا دامنه‌های خبری است. سایر کلمات بیشتر حالت عمومی و روزمره دارند و در پردازش‌های معنایی نقش کلیدی دارند.


#### مزایا و محدودیت‌ها برای بخش‌های بعدی پروژه

مزایای این پیش‌پردازش برای مراحل بعدی پروژه به شرح زیر است:  

- در بخش دوم که از **pretrained word embedding** استفاده می‌کنم، حذف نویزها و کلمات کم‌اهمیت باعث می‌شود embeddingها دقیق‌تر و بر اساس کلمات کلیدی باشند و همسایه‌های معنایی واقعی‌تر به دست آیند.  
- در بخش سوم که از **Learning to Rank** برای ارزیابی مستندات استفاده می‌کنم، کاهش تعداد واژگان و حذف کلمات بی‌ربط باعث می‌شود ویژگی‌های embedding برای query و document بهینه‌تر شوند و مدل سریع‌تر و با دقت بیشتری آموزش ببیند.  

محدودیت‌ها نیز شامل این موارد است:  

- ممکن است برخی کلمات کوتاه یا کم‌تکرار که معنای مهمی دارند حذف شوند و باعث از دست رفتن اطلاعات جزئی شوند.  
- اگر روابط معنایی خاص بین کلمات نادر در متن وجود داشته باشد، مدل‌های بعدی ممکن است آن‌ها را تشخیص ندهند و تأثیر اندکی بر عملکرد نهایی داشته باشند.  
- پردازش اولیه برای مجموعه داده‌های بزرگ زمان‌بر است و نیاز به حافظه کافی دارد، هرچند که مزیت کاهش نویز و تسهیل یادگیری بیشتر است.  

در مجموع، این پیش‌پردازش یک پایه قوی برای استخراج ویژگی‌های معنایی و رتبه‌بندی مستندات فراهم می‌کند و در عین حال باید در مراحل بعدی مراقب از دست رفتن اطلاعات جزئی باشیم.

</div>


In [331]:
class PrepEngine:
    def __init__(self,
                 segment_mode: str = "doc",
                 strip_metadata: bool = True,
                 drop_stopwords: bool = True,
                 min_token_length: int = 2,
                 min_token_frequency: int = 5,
                 max_vocabulary: int | None = None):
        self.segment_mode = segment_mode
        self.strip_metadata = strip_metadata
        self.drop_stopwords = drop_stopwords
        self.min_token_length = min_token_length
        self.min_token_frequency = min_token_frequency
        self.max_vocabulary = max_vocabulary
        self._sent_split = _re.compile(r"[.!?]+\s+")
        self._noise_re = _re.compile(r"[^a-z0-9\s]+")
        self._space_re = _re.compile(r"\s+")
        self._dataset = None
        self.segments_text = []
        self.segments_tokens = []

    def fetch_corpus(self):
        remove_opts = ("headers", "footers", "quotes") if self.strip_metadata else None
        self._dataset = _fetch_news(
            subset="all",
            shuffle=True,
            random_state=42,
            remove=remove_opts
        )
        return self._dataset

    def _normalize(self, piece: str) -> str:
        p = piece.strip().lower()
        p = self._noise_re.sub(" ", p)
        p = self._space_re.sub(" ", p).strip()
        return p

    def _segment_piece(self, piece: str) -> list[str]:
        if not piece or not piece.strip():
            return []
        if self.segment_mode == "doc":
            return [piece.strip()]
        return [s.strip() for s in self._sent_split.split(piece) if s.strip()]

    def _tokenize_piece(self, piece: str) -> list[str]:
        n = self._normalize(piece)
        if not n:
            return []
        tokens = n.split()
        if self.drop_stopwords:
            tokens = [t for t in tokens if t not in _STOPWORDS]
        tokens = [t for t in tokens if len(t) >= self.min_token_length]
        return tokens

    def prepare(self):
        if self._dataset is None:
            self.fetch_corpus()
        segs = []
        toks_acc = []
        for doc in self._dataset.data:
            for seg in self._segment_piece(doc):
                toks = self._tokenize_piece(seg)
                if toks:
                    segs.append(seg)
                    toks_acc.append(toks)
        self.segments_text = segs
        self.segments_tokens = toks_acc
        return segs, toks_acc

    def build_dictionary(self):
        cnt = _Counter()
        for toks in self.segments_tokens:
            cnt.update(toks)
        items = [(w, c) for w, c in cnt.items() if c >= self.min_token_frequency]
        items.sort(key=lambda x: (-x[1], x[0]))
        if self.max_vocabulary is not None:
            items = items[:self.max_vocabulary]
        vocab_map = {w: i for i, (w, _) in enumerate(items)}
        freq_df = _pd.DataFrame(items, columns=["term", "count"])
        return vocab_map, freq_df

    def report(self, top_n: int = 30):
        vocab_map, freq_df = self.build_dictionary()
        summary = _pd.DataFrame(
            {"metric": ["segments_count", "vocab_size"],
             "value": [len(self.segments_text), len(vocab_map)]}
        )
        top_k = freq_df.head(top_n).copy()
        return summary, top_k


In [332]:
engine = PrepEngine(segment_mode="doc", strip_metadata=True, drop_stopwords=True,
                    min_token_length=2, min_token_frequency=5, max_vocabulary=None)
engine.fetch_corpus()
engine.prepare()
summary_df, top30_df = engine.report(top_n=30)

summary_fig = _go.Figure(data=_go.Table(
    header=dict(values=["Metric", "Value"], fill_color='lightblue', align='left'),
    cells=dict(values=[summary_df.metric, summary_df.value], fill_color='lightcyan', align='left')
))
summary_fig.update_layout(title_text="Preprocessing Summary")

vocab_fig = _go.Figure(data=_go.Table(
    header=dict(values=["Rank", "Term", "Count"], fill_color='lightgreen', align='left'),
    cells=dict(values=[list(range(1, len(top30_df)+1)), top30_df.term.tolist(), top30_df["count"].tolist()],
               fill_color='honeydew', align='left')
))
vocab_fig.update_layout(title_text="Top-30 Vocabulary Terms", height=900)

summary_fig.show()
vocab_fig.show()


## <div style="text-align: right; direction: rtl;">استخراج روابط Paradigmatic با pseudo-document</div>


<div dir="rtl">

در این بخش، هدف بررسی و تحلیل **روابط paradigmatic** بین واژگان منتخب است. برای این منظور ابتدا مجموعه‌ای از **۲۰ واژه پرتکرار و معنادار** از داده‌های متنی خود استخراج شد که شامل کلماتی مانند `'ax'`, `'like'`, `'don'`, `'people'`, `'just'`, `'know'` و... هستند. این واژه‌ها به عنوان کلمات هدف (target keywords) انتخاب شدند تا بتوانیم روابط معنایی آن‌ها را در فضای متنی مدل‌سازی کنیم.

#### ساخت Pseudo-Document

برای هر واژه هدف، تمام بافت‌هایی که واژه در آن‌ها ظاهر شده است بررسی شد. هر بار که واژه هدف در یک **segment** دیده شد، تمامی واژه‌های موجود در **پنجره‌ای با شعاع WINDOW_RADIUS = 2** اطراف آن جمع‌آوری شدند تا یک **pseudo-document** ایجاد شود. در واقع، این pseudo-document شامل مجموعه‌ای از واژه‌های هم‌جوار است که می‌توانند نماینده **context معنایی** واژه هدف باشند.

<div align="center" dir="ltr">

$$
\text{pseudo\_document}(w) = \bigcup_{\text{segment}} \{ \text{context}_{\text{window}}(w) \} \setminus \{w\}
$$

</div>


<div dir="rtl">

پس از ایجاد pseudo-documentها، طول هر pseudo-document محاسبه شد و جدول زیر نشان‌دهنده تعداد واژه‌های هم‌جوار هر واژه هدف است:

| Keyword | Pseudo-document Length |
|---------|-----------------------|
| ax      | 249603                |
| like    | 25629                 |
| people  | 25561                 |
| don     | 25360                 |
| just    | 23882                 |
| know    | 22353                 |
| use     | 19893                 |
| think   | 19334                 |
| time    | 19192                 |
| max     | 18903                 |
| ...     | ...                   |

این جدول نشان می‌دهد که واژه `'ax'` بیشترین تعداد context را داشته و واژه `'say'` کمترین تعداد را داشته است.


</div>


In [333]:
WINDOW_RADIUS = 2
TOP_NEIGHBORS = 10
ANALYSIS_COUNT = 5
NUM_TARGET_KEYWORDS = 20

target_keywords = top30_df["term"].head(NUM_TARGET_KEYWORDS).tolist()
target_keywords


['ax',
 'like',
 'don',
 'people',
 'just',
 'know',
 'use',
 'think',
 'time',
 'max',
 'does',
 'new',
 'good',
 'edu',
 'god',
 'way',
 'make',
 've',
 'used',
 'say']

In [334]:
def construct_pseudo_document(keyword: str, text_atoms: list[list[str]], radius: int) -> list[str]:
    context_pool = []
    for segment in text_atoms:
        positions = _np.where(_np.array(segment) == keyword)[0]
        for pos in positions:
            start, end = max(0, pos - radius), min(len(segment), pos + radius + 1)
            context_pool.extend(segment[start:end])
            context_pool.remove(keyword) if keyword in context_pool else None
    return context_pool

pseudo_docs_atoms = [construct_pseudo_document(k, engine.segments_tokens, WINDOW_RADIUS) for k in target_keywords]

pseudo_len_df = _pd.DataFrame({
    "keyword": target_keywords,
    "pseudo_doc_len": [len(d) for d in pseudo_docs_atoms]
}).sort_values("pseudo_doc_len", ascending=False)

fig_pseudo = _go.Figure(data=_go.Table(
    header=dict(values=["Keyword", "Pseudo-document Length"], fill_color='lavender', align='left'),
    cells=dict(values=[pseudo_len_df.keyword, pseudo_len_df.pseudo_doc_len], fill_color='lavenderblush', align='left')
))
fig_pseudo.update_layout(title_text="Pseudo-document Lengths per Keyword")
fig_pseudo.show()


<div dir="rtl">


#### محاسبه TF-IDF و Cosine Similarity

با استفاده از pseudo-documentها، یک **ماتریس TF-IDF** ایجاد شد تا نمایه‌ای عددی از اهمیت هر واژه در contextها به دست آید. سپس، **cosine similarity** بین بردارهای TF-IDF واژه‌های هدف محاسبه شد تا بتوان **همسایه‌های نزدیک معنایی** هر واژه را شناسایی کرد:

<div align="center" dir="ltr">

$$
\text{sim}(w_i, w_j) = \frac{\vec{v}_{w_i} \cdot \vec{v}_{w_j}}{\|\vec{v}_{w_i}\| \, \|\vec{v}_{w_j}\|}
$$

</div>


<div dir="rtl">

با این روش، برای هر یک از ۵ واژه منتخب (`'ax'`, `'like'`, `'don'`, `'people'`, `'just'`) **۱۰ همسایه نزدیک** مشخص شد. به عنوان مثال، همسایگان نزدیک واژه `'ax'` عبارتند از `'max'` با similarity تقریبی 0.999 و سایر واژه‌ها با مقادیر بسیار کمتر.

#### تحلیل روابط معنایی

مشاهده می‌کنیم که برای واژه `'like'`، همسایگانی مانند `'just'`, `'way'`, `'people'`, `'think'` با similarity‌های بین 0.548 تا 0.669 یافت شدند. این نشان‌دهنده آن است که این واژه‌ها از نظر معنایی به هم نزدیک هستند و اغلب در contextهای مشابه استفاده شده‌اند. به طور مشابه، واژه `'don'` همسایگانی مانند `'does'`, `'people'`, `'just'` و `'way'` دارد که نشان‌دهنده ارتباط معنایی منطقی است.

در بسیاری موارد، واژه‌های همسایه، **قابل جایگزینی در context** واژه اصلی نیستند، اما از نظر معنایی نزدیک و مرتبط هستند. این تفاوت بین هم‌معنی مطلق و هم‌جوار معنایی با استفاده از pseudo-documentها آشکار می‌شود.

</div>


In [335]:
tfidf_processor = _TFIDF(
    tokenizer=lambda x: x,
    preprocessor=lambda x: x,
    token_pattern=None,
    lowercase=False
)
tfidf_matrix = tfidf_processor.fit_transform(pseudo_docs_atoms)
similarity_matrix = _cos_sim(tfidf_matrix)
similarity_matrix.shape


(20, 20)

In [336]:
def find_top_neighbors(sim_row: _np.ndarray, terms: list[str], self_idx: int, top_k: int):
    sorted_idx = _np.argsort(-sim_row)
    sorted_idx = [i for i in sorted_idx if i != self_idx][:top_k]
    return [(terms[i], float(sim_row[i])) for i in sorted_idx]

analysis_keywords = target_keywords[:ANALYSIS_COUNT]
analysis_indices = [target_keywords.index(k) for k in analysis_keywords]

neighbors_map = {
    k: find_top_neighbors(similarity_matrix[idx], target_keywords, idx, TOP_NEIGHBORS)
    for k, idx in zip(analysis_keywords, analysis_indices)
}

neighbor_tables = {k: _pd.DataFrame(v, columns=["Neighbor", "Similarity"]) for k, v in neighbors_map.items()}

fig = _make_subplots(
    rows=1, cols=len(analysis_keywords),
    subplot_titles=analysis_keywords,
    specs=[[{"type": "table"}]*len(analysis_keywords)]
)

for i, k in enumerate(analysis_keywords):
    df = neighbor_tables[k]
    fig.add_trace(_go.Table(
        header=dict(values=["Neighbor", "Similarity"],
                    fill_color='palegreen', align='left', font=dict(size=14)),
        cells=dict(values=[df.Neighbor, df.Similarity.round(6)],
                   fill_color='mintcream', align='left', font=dict(size=12))
    ), row=1, col=i+1)

fig.update_layout(
    width=300*len(analysis_keywords),
    height=450,
    title_text="Top Neighbors for Selected Keywords",
    margin=dict(l=20, r=20, t=60, b=20)
)

fig.show()




<div dir="rtl">

#### تجزیه و تحلیل PCA و نمای دو بعدی

برای درک بهتر روابط معنایی، بردارهای TF-IDF همان ۵ واژه و همسایگان نزدیکشان با استفاده از **Principal Component Analysis (PCA)** به دو بعد کاهش یافتند. در نمودار ۲ بعدی، هر نقطه نماینده یک واژه است و فاصله بین نقاط نمایانگر **proximity معنایی** است. رنگ و شدت نقاط برای همسایگان بر اساس **cosine similarity** با واژه anchor تغییر می‌کند تا میزان نزدیکی معنایی به صورت بصری قابل بررسی باشد.

مشاهده می‌کنیم که:

* برای واژه `'ax'`، همسایه اصلی `'max'` بسیار نزدیک anchor قرار گرفته است، در حالی که دیگر همسایگان پراکنده‌تر هستند.
* واژه `'like'` و همسایگانش خوشه‌ای نسبی شکل داده‌اند که ارتباط معنایی بین آن‌ها را نشان می‌دهد.
* واژه `'people'` و `'just'` نیز در نزدیکی هم قرار دارند و نقاط مربوط به `'think'`, `'know'` نیز با شدت کمتر نزدیک آن‌ها هستند.

این نتایج نشان می‌دهد که **فاصله در فضای PCA با شباهت معنایی واقعی واژه‌ها هماهنگ است** و خوشه‌هایی از واژه‌های مرتبط به طور طبیعی شکل گرفته‌اند.

نتیجه کلی این است که واژه‌هایی که از نظر معنایی نزدیک‌اند، در نمودار PCA نیز در کنار هم قرار دارند و می‌توان خوشه‌ها و ارتباطات معنایی را به صورت بصری بررسی کرد.

</div>


In [337]:
for anchor_word in analysis_keywords:
    df_neighbors = neighbor_tables[anchor_word].copy()
    
    terms_to_plot = [anchor_word] + df_neighbors["Neighbor"].tolist()
    similarities = [1.0] + df_neighbors["Similarity"].tolist()

    plot_idx = [target_keywords.index(t) for t in terms_to_plot]
    X_subset = tfidf_matrix[plot_idx].toarray()

    pca_model = _PCA(n_components=2, random_state=2025)
    coords_2d = pca_model.fit_transform(X_subset)

    df_plot = _pd.DataFrame({
        "term": terms_to_plot,
        "pc1": coords_2d[:, 0],
        "pc2": coords_2d[:, 1],
        "similarity": similarities
    })

    fig = _go.Figure()

    fig.add_trace(_go.Scatter(
        x=[df_plot.pc1[0]],
        y=[df_plot.pc2[0]],
        mode="markers+text",
        text=[df_plot.term[0]],
        textposition="top center",
        marker=dict(size=24, color="crimson", symbol="diamond", line=dict(width=2)),
        name="Anchor"
    ))

    fig.add_trace(_go.Scatter(
        x=df_plot.pc1[1:],
        y=df_plot.pc2[1:],
        mode="markers+text",
        text=df_plot.term[1:],
        textposition="top center",
        marker=dict(
            size=16,
            color=df_plot.similarity[1:],
            colorscale="Blues",
            cmin=0,
            cmax=1,
            colorbar=dict(title="Cosine Similarity", len=0.7, thickness=18),
            line=dict(width=1)
        ),
        name="Neighbor"
    ))

    for _, row in df_plot.iloc[1:].iterrows():
        fig.add_trace(_go.Scatter(
            x=[df_plot.pc1[0], row.pc1],
            y=[df_plot.pc2[0], row.pc2],
            mode="lines",
            line=dict(width=1, dash="dot", color="gray"),
            showlegend=False,
            opacity=row.similarity
        ))

    fig.update_layout(
        title=f"Anchor '{anchor_word}' with Neighbors — PCA & Cosine Similarity",
        xaxis_title="PC1",
        yaxis_title="PC2",
        width=900,
        height=700,
        margin=dict(l=40, r=40, t=80, b=40)
    )

    fig.show()


## <div style="text-align: right; direction: rtl;">استخراج روابط Syntagmatic با Mutual Information</div>


<div dir="rtl">

در این بخش، هدف بررسی روابط **Syntagmatic** بین واژه‌ها است. برای این منظور ابتدا یک مدل `SyntagmaticAnalyzer` تعریف شد که قابلیت پردازش segmentهای متنی و واژه‌های هدف را دارد و بر اساس حضور همزمان واژه‌ها در segmentها، روابط معنایی را با **مقدار اطلاعات متقابل (Mutual Information)** ارزیابی می‌کند.

برای هر واژه یک متغیر دودویی روی segmentها تعریف کردیم: اگر واژه در segment ظاهر شود مقدار آن ۱ و در غیر این صورت ۰ است. سپس برای جفت‌هایی از واژه‌ها که حداقل در ۱۸ segment حضور داشتند، فراوانی حضور هر واژه و حضور همزمان هر دو را شمارش کردیم و با استفاده از یک smoothing کوچک (\(\alpha = 10^{-5}\)) احتمال‌ها را تخمین زدیم. مقدار Mutual Information برای هر جفت واژه با فرمول زیر محاسبه شد:


<div align="center" dir="ltr">

$$
\text{MI}(w,u) =
p_{11}\log_2\frac{p_{11}}{p_{1\_}p_{\_1}}
+
p_{10}\log_2\frac{p_{10}}{p_{1\_}p_{\_0}}
+
p_{01}\log_2\frac{p_{01}}{p_{0\_}p_{\_1}}
+
p_{00}\log_2\frac{p_{00}}{p_{0\_}p_{\_0}}
$$


</div>


<div dir="rtl">

که در آن \(p_{11}\) احتمال حضور همزمان دو واژه، \(p_{10}\) و \(p_{01}\) احتمال حضور تنها یکی از واژه‌ها و \(p_{00}\) احتمال عدم حضور هر دو واژه است.

پس از محاسبه MI برای تمام جفت‌ها، بر روی پنج واژه پرکاربرد تمرکز کردیم: `like`, `just`, `don`, `know`, و `think`. برای هر واژه، ده همسایه Syntagmatic برتر که بالاترین MI را داشتند، استخراج شد. جدول زیر خلاصه‌ای از نتایج اولیه است:

| query_word | rank | neighbor | MI | cooc_segments(n11) | df(neighbor) |
|------------|------|---------|----|------------------|--------------|
| like       | 1    | just    | 0.026903 | 1585 | 4082 |
| like       | 2    | people  | 0.025748 | 1256 | 2988 |
| like       | 3    | don     | 0.023229 | 1486 | 3894 |
| just       | 1    | don     | 0.030988 | 1546 | 3894 |
| know       | 1    | don     | 0.045188 | 1616 | 3807 |
| think      | 1    | don     | 0.041155 | 1391 | 3894 |

این جدول نشان می‌دهد که واژه‌هایی که بیشترین مقدار MI را با یک واژه خاص دارند، معمولاً در جملات مشابه و در کنار آن واژه به‌کار رفته‌اند. برای مثال، `like` و `just` بیشترین حضور همزمان را دارند، که بیانگر استفاده مشترک آنها در contextهای مشابه است.

<div dir="rtl">


In [338]:
class SyntagmaticAnalyzer:
    def __init__(self, text_atoms: list[list[str]], target_words: list[str], min_seg: int = 20, top_k: int = 10, smoothing: float = 1e-5):
        self.text_atoms = text_atoms
        self.target_words = target_words
        self.min_segments = min_seg
        self.top_k = top_k
        self.alpha = smoothing
        self.word_df = None
        self.cooc_matrix = None

    def compute_document_frequencies(self):
        counts = _Counter()
        for segment in self.text_atoms:
            unique_words = set(segment)
            counts.update(unique_words)
        self.word_df = counts
        return counts

    def compute_cooccurrences(self):
        cooc = {w: _Counter() for w in self.target_words}
        for segment in self.text_atoms:
            unique_words = set(segment)
            for w in self.target_words:
                if w in unique_words:
                    for u in unique_words:
                        if u != w:
                            cooc[w][u] += 1
        self.cooc_matrix = cooc
        return cooc

    def mutual_info(self, n11, n10, n01, n00):
        n11 += self.alpha
        n10 += self.alpha
        n01 += self.alpha
        n00 += self.alpha
        N = n11 + n10 + n01 + n00
        p11, p10, p01, p00 = n11/N, n10/N, n01/N, n00/N
        p1_, p0_ = p11+p10, p01+p00
        p_1, p_0 = p11+p01, p10+p00
        return (p11*_math.log2(p11/(p1_*p_1)) +
                p10*_math.log2(p10/(p1_*p_0)) +
                p01*_math.log2(p01/(p0_*p_1)) +
                p00*_math.log2(p00/(p0_*p_0)))

    def analyze(self):
        M = len(self.text_atoms)
        results = {}
        for w in self.target_words:
            df_w = self.word_df[w]
            neighbors = []
            for u, n11 in self.cooc_matrix[w].items():
                if n11 < self.min_segments:
                    continue
                df_u = self.word_df[u]
                n10 = df_w - n11
                n01 = df_u - n11
                n00 = M - (n11 + n10 + n01)
                if min(n10, n01, n00) < 0:
                    continue
                mi = self.mutual_info(n11, n10, n01, n00)
                neighbors.append((u, mi, n11, df_u))
            neighbors.sort(key=lambda x: x[1], reverse=True)
            results[w] = neighbors[:self.top_k]
        return results


In [ ]:
len(engine.segments_tokens)

18294

In [ ]:

analyzer = SyntagmaticAnalyzer(engine.segments_tokens, target_keywords, min_seg=18, top_k=10, smoothing=1e-5)
df_counts = analyzer.compute_document_frequencies()
df_cooc = analyzer.compute_cooccurrences()

top_words = sorted(df_counts.items(), key=lambda x: x[1], reverse=True)[:10]
_pd.DataFrame({"word": [w for w, _ in top_words],
               "segment_count": [c for _, c in top_words]})


word  segment_count
0    like           4213
1    just           4082
2     don           3894
3    know           3807
4   think           3145
5    does           2994
6  people           2988
7    time           2951
8     use           2706
9    good           2558

In [ ]:
target_keywords = [w for w, _ in top_words]

analyzer.target_words = target_keywords
syntag_results = analyzer.analyze()

rows = []
for w in target_keywords:
    neighbors = syntag_results.get(w, [])
    for rank, (neighbor, mi, n11, df_neighbor) in enumerate(neighbors, start=1):
        rows.append({
            "query_word": w,
            "rank": rank,
            "neighbor": neighbor,
            "MI": mi,
            "cooc_segments(n11)": n11,
            "df(neighbor)": df_neighbor
        })

df_syntag_report = _pd.DataFrame(rows)


In [ ]:
fig_syntag = _make_subplots(
    rows=1, cols=min(ANALYSIS_COUNT, len(target_keywords)),
    subplot_titles=target_keywords[:ANALYSIS_COUNT],
    specs=[[{"type": "table"}]*min(ANALYSIS_COUNT, len(target_keywords))]
)

for i, w in enumerate(target_keywords[:ANALYSIS_COUNT]):
    df_tmp = df_syntag_report[df_syntag_report["query_word"] == w]
    if df_tmp.empty:
        continue
    fig_syntag.add_trace(_go.Table(
        header=dict(values=["Neighbor", "MI", "cooc_segments(n11)", "df(neighbor)"],
                    fill_color='lightcoral', align='left'),
        cells=dict(values=[
            df_tmp["neighbor"],
            df_tmp["MI"].round(6),
            df_tmp["cooc_segments(n11)"],
            df_tmp["df(neighbor)"]
        ], fill_color='mistyrose', align='left')
    ), row=1, col=i+1)

fig_syntag.update_layout(
    width=350*ANALYSIS_COUNT,
    height=400,
    title_text="Top Syntagmatic Neighbors per Most Frequent Words",
    margin=dict(l=20, r=20, t=60, b=20)
)
fig_syntag.show()


<div dir="rtl">

### مقایسه بین همسایه‌های Syntagmatic و Paradigmatic

در این بخش، به تحلیل تفاوت‌ها و همپوشانی بین همسایه‌های **Syntagmatic** و **Paradigmatic** می‌پردازیم.


| word  | syntagmatic_neighbors | paradigmatic_neighbors | only_syntagmatic | only_paradigmatic | common |
|-------|---------------------|----------------------|-----------------|-----------------|--------|
| like  | looks, know, people, look, don, just, make, things, really, sounds | know, people, just, don, good, does, time, use, think, like | looks, look, make, things, really, sounds | good, does, time, use, think | know, just, people, don |
| just  | like, say, people, don, good, way, going, really, time, good | like, know, people, don, good, does, time, use, think | say, going, really, way | know, use, does | like, people, don, good, time, think |
| don   | say, know, like, people, just, way, want, things, really, time | like, know, people, just, good, does, time, use, think | say, way, want, things, really | time, does, use, good | like, know, people, just, think |
| know  | like, say, people, let, don, just, want, does, things, time | like, people, just, don, good, does, time, use, think | say, want, let, things | use, good, think | like, people, don, just, does, time |
| think | say, like, people, don, just, good, way, going, time, good | like, know, people, just, don, good, does, time, use | say, going, really, way | know, use, does | like, people, don, just, good, time |

با بررسی این جدول می‌توان نکات زیر را استخراج کرد:

- همسایه‌های **Syntagmatic** واژه‌هایی هستند که در کنار واژه اصلی در متن ظاهر شده‌اند و نشان‌دهنده حضور همزمان در context هستند.
- همسایه‌های **Paradigmatic** واژه‌هایی با معنی مشابه هستند که می‌توانند جایگزین واژه اصلی شوند و الزاماً در کنار آن ظاهر نمی‌شوند.
- مقایسه ستون‌های `only_syntagmatic` و `only_paradigmatic` نشان می‌دهد که برخی واژه‌ها منحصر به روابط همزمان هستند و برخی صرفاً مشابه معنایی هستند.
- ستون `common` نشان‌دهنده واژه‌هایی است که همزمان و هم معنایی با واژه اصلی مرتبط هستند.

برای نمونه، واژه `like` دارای همسایه‌های Syntagmatic مانند `looks` و `make` است که بیشتر در همان جملات ظاهر شده‌اند، در حالی که همسایه‌های Paradigmatic مانند `good` و `time` بیشتر نمایانگر جایگزین‌های معنایی هستند. این تحلیل ترکیبی، بینش عمیقی نسبت به ساختار معنایی متن‌ها و نحوه همبستگی واژه‌ها ارائه می‌دهد و نشان می‌دهد که استفاده همزمان و شباهت معنایی، هر دو بعد مهم در درک معانی واژه‌ها هستند.

</div>


In [ ]:
FOCUS_COUNT = 5

top_words = sorted(df_counts.items(), key=lambda x: x[1], reverse=True)
focus_words = [w for w, _ in top_words[:FOCUS_COUNT]]

focus_words


['like', 'just', 'don', 'know', 'think']

In [ ]:
pseudo_docs_atoms = [
    construct_pseudo_document(k, engine.segments_tokens, WINDOW_RADIUS)
    for k in target_keywords
]

tfidf_matrix = tfidf_processor.fit_transform(pseudo_docs_atoms)
similarity_matrix = _cos_sim(tfidf_matrix)


In [ ]:
records = []
analysis_keywords = target_keywords[:ANALYSIS_COUNT]
analysis_indices = [target_keywords.index(k) for k in analysis_keywords]

neighbors_map = {}
for k, idx in zip(analysis_keywords, analysis_indices):
    neighbors = find_top_neighbors(similarity_matrix[idx], target_keywords, idx, TOP_NEIGHBORS)
    neighbors_map[k] = neighbors
    for tgt_word, score in neighbors:
        records.append({
            "target_word": k,
            "neighbor": tgt_word,
            "score": score,
            "relation": "paradigmatic"
        })

df_paradigmatic = _pd.DataFrame(records)


# df_paradigmatic

In [ ]:
analyzer_comparison = SyntagmaticAnalyzer(engine.segments_tokens, target_keywords, min_seg=18, top_k=10, smoothing=1e-5)
df_counts = analyzer_comparison.compute_document_frequencies()
df_cooc = analyzer_comparison.compute_cooccurrences()

top_words = sorted(df_counts.items(), key=lambda x: x[1], reverse=True)[:10]
_pd.DataFrame({"word": [w for w, _ in top_words],
               "segment_count": [c for _, c in top_words]})


analyzer_comparison.target_words = focus_words
syntag_results = analyzer_comparison.analyze()

df_synt = _pd.concat([
    _pd.DataFrame(v, columns=["neighbor", "MI", "cooc_segments", "df_neighbor"])
      .assign(target_word=w, relation="syntagmatic")
    for w, v in syntag_results.items()
], ignore_index=True)

# df_synt

In [ ]:
fig = _make_subplots(
    rows=2, cols=len(analysis_keywords),
    subplot_titles=[f"{k} (Paradigmatic)" for k in analysis_keywords] +
                   [f"{k} (Syntagmatic)" for k in analysis_keywords],
    specs=[[{"type": "table"}]*len(analysis_keywords)]*2
)

for i, k in enumerate(analysis_keywords):
    df_para = df_paradigmatic[df_paradigmatic.target_word == k][["neighbor", "score", "relation"]]
    fig.add_trace(_go.Table(
        header=dict(values=["Neighbor", "Score", "Relation"], fill_color='palegreen', align='left', font=dict(size=14)),
        cells=dict(values=[df_para.neighbor, df_para.score.round(6), df_para.relation], fill_color='mintcream', align='left', font=dict(size=12))
    ), row=1, col=i+1)

    df_synt_k = df_synt[df_synt.target_word == k][["neighbor", "MI", "relation"]]
    fig.add_trace(_go.Table(
        header=dict(values=["Neighbor", "MI", "Relation"], fill_color='lightblue', align='left', font=dict(size=14)),
        cells=dict(values=[df_synt_k.neighbor, df_synt_k.MI.round(6), df_synt_k.relation],
                   fill_color='lavender', align='left', font=dict(size=12))
    ), row=2, col=i+1)

fig.update_layout(
    width=350*len(analysis_keywords),
    height=800,
    title_text="Paradigmatic and Syntagmatic Neighbors for Selected Keywords",
    margin=dict(l=20, r=20, t=60, b=20)
)

fig.show()


In [ ]:
comparison_rows = []

for w in focus_words:
    para_set = set(df_paradigmatic[df_paradigmatic.target_word == w]["neighbor"])
    synt_set = set(df_synt[df_synt.target_word == w]["neighbor"])

    comparison_rows.append({
        "word": w,
        "syntagmatic_neighbors": synt_set,
        "paradigmatic_neighbors": para_set,
        "only_syntagmatic": synt_set - para_set,
        "only_paradigmatic": para_set - synt_set,
        "common": synt_set & para_set
    })

df_comparison_display = _pd.DataFrame(comparison_rows)

for col in ["syntagmatic_neighbors", "paradigmatic_neighbors", "only_syntagmatic", "only_paradigmatic", "common"]:
    df_comparison_display[col] = df_comparison_display[col].apply(lambda x: ", ".join(x))

fig = _go.Figure(data=[_go.Table(
    header=dict(values=["Word", "Syntagmatic Neighbors", "Paradigmatic Neighbors", 
                        "Only Syntagmatic", "Only Paradigmatic", "Common"],
                fill_color='lightblue',
                align='left'),
    cells=dict(values=[df_comparison_display.word,
                       df_comparison_display.syntagmatic_neighbors,
                       df_comparison_display.paradigmatic_neighbors,
                       df_comparison_display.only_syntagmatic,
                       df_comparison_display.only_paradigmatic,
                       df_comparison_display.common],
               fill_color='lavender',
               align='left'))
])

fig.update_layout(width=1400, height=400, title_text="Comparison of Syntagmatic vs Paradigmatic Neighbors")
fig.show()


# <div style="text-align: center; direction: rtl;"><h1 align="center" style="font-size: 24px; padding: 20px;">━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>سوال دوم - کار با PRETRAINED WORD EMBEDDING  <br>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</h1></div>


## <div style="text-align: right; direction: rtl;">بارگذاری مدل GloVe</div>



<div dir="rtl">


در این بخش، هدف  بارگذاری مدل **GloVe 6B با بردارهای ۱۰۰ بعدی** و بررسی میزان پوشش واژگان پیکره **20 Newsgroups** بود. برای مدیریت فرآیند دانلود، استخراج و بارگذاری فایل‌های مدل، یک کلاس **GloVeManager** پیاده‌سازی شد که تمامی مراحل به صورت یکپارچه و شی‌گرا انجام می‌دهد. این کلاس ابتدا مسیر ذخیره‌سازی فایل‌ها را ایجاد می‌کند، سپس اگر فایل فشرده GloVe موجود نباشد آن را از وب‌سایت Stanford دانلود می‌کند و پس از آن فایل متنی حاوی بردارهای ۱۰۰ بعدی را استخراج می‌نماید.

پس از آماده‌سازی فایل‌ها، بردارهای عددی هر واژه در دیکشنری **glove_vectors** ذخیره شدند. تعداد کل واژگان موجود در مدل **۴۰۰۰۰۰** و ابعاد هر بردار **۱۰۰** است:



<div align="center" dir="ltr">

$$
\text{Vocabulary Size} = 400000
$$
$$
\text{Embedding Dimension} = 100
$$


</div>


<div dir="rtl">

برای تحلیل واژگان پیکره، ابتدا با استفاده از کلاس **PrepEngine** متن‌ها به واحدهای معنایی (segments) تقسیم شد و کلمات دارای طول کمتر از ۳ کاراکتر و با فرکانس کمتر از ۵ حذف شدند. سپس یک دیکشنری از واژگان و فراوانی آن‌ها ساخته شد. تعداد کل واژگان پس از پیش‌پردازش **۲۹۰۱۳** بود و متداول‌ترین ۲۰ کلمه شامل `like`, `don`, `people`, `just`, `know` و غیره بودند.

در مرحله بعد، میزان پوشش هر واژه پیکره توسط مدل GloVe بررسی شد. تعداد واژگانی که در مدل موجود بودند **۲۵۴۱۰** و نسبت پوشش کل واژگان برابر با **۸۷.۵۸٪** بود:



<div align="center" dir="ltr">

$$
\text{Coverage Ratio} = \frac{25410}{29013} \approx 0.8758 \approx 87.58\%
$$


</div>


<div dir="rtl">
این نسبت نشان می‌دهد که مدل GloVe 6B بخش عمده‌ای از واژگان پیکره را پوشش می‌دهد و می‌تواند برای پروژه‌های تحلیل معنایی و یادگیری ماشین ابزار مناسبی باشد. برخی از کلمات خارج از دایره (OOV) شامل شناسه‌ها و کلمات خاص بودند، مانند `g9v`, `b8f`, `1d9`, `34u`, `0t` و ... که نشان‌دهنده واژگان نادر یا ترکیبی است که در مدل GloVe وجود ندارد.

در مجموع، این بخش موفق شد نه تنها مدل GloVe را به صورت کامل بارگذاری کند، بلکه یک تحلیل عددی دقیق از پوشش واژگان ارائه دهد و نشان دهد که تقریباً **۸۸٪** واژگان پیکره **20 Newsgroups** در این مدل قابل استفاده هستند، که این امر امکان بهره‌گیری از بردارهای ۱۰۰ بعدی برای تحلیل‌های معنایی پیشرفته را فراهم می‌آورد.

</div>


In [19]:
class GloVeManager:
    def __init__(self, base_path, zip_name, txt_name, dim=100):
        self.base_dir = base_path
        self.zip_file = _os.path.join(base_path, zip_name)
        self.txt_file = _os.path.join(base_path, txt_name)
        self.dim = dim
        _os.makedirs(base_path, exist_ok=True)

    def download_zip(self, url):
        current_size = _os.path.getsize(self.zip_file) if _os.path.exists(self.zip_file) else 0
        headers = {"Range": f"bytes={current_size}-"} if current_size > 0 else {}
        with _requests.get(url, headers=headers, stream=True, timeout=60) as resp:
            resp.raise_for_status()
            total = resp.headers.get("Content-Range")
            total_bytes = int(total.split("/")[-1]) if total else int(resp.headers.get("Content-Length", 0)) + current_size
            mode = "ab" if current_size > 0 else "wb"
            downloaded = current_size
            with open(self.zip_file, mode) as f:
                for chunk in resp.iter_content(chunk_size=1024*1024):
                    if chunk:
                        f.write(chunk)
                        downloaded += len(chunk)
                        percent = downloaded / total_bytes * 100 if total_bytes > 0 else 0
                        print(f"\rDownloading: {downloaded/(1024**2):.2f}/{total_bytes/(1024**2):.2f} MB ({percent:.2f}%)", end="")
        print("\nDownload complete")
    
    def extract_txt(self):
        if not _os.path.exists(self.txt_file):
            with _zip.ZipFile(self.zip_file, "r") as zf:
                zf.extract(_os.path.basename(self.txt_file), path=self.base_dir)
        return self.txt_file

    def load_embeddings(self):
        vectors = {}
        with open(self.txt_file, "r", encoding="utf-8") as f:
            for ln in f:
                parts = ln.rstrip().split(" ")
                w = parts[0]
                vec = _np.asarray(parts[1:], dtype=_np.float32)
                if vec.shape[0] == self.dim:
                    vectors[w] = vec
        return vectors



In [20]:
glove_mgr = GloVeManager(r"C:\temp\glove_custom", "glove.6B.zip", "glove.6B.100d.txt", dim=100)

if not _os.path.exists(glove_mgr.zip_file):
    glove_mgr.download_zip("https://nlp.stanford.edu/data/glove.6B.zip")
else:
    print("Zip file already exists, skipping download.")

glove_path = glove_mgr.extract_txt()
lexicon_raw  = glove_mgr.load_embeddings()
_pd.DataFrame({"Vocabulary Size": [len(lexicon_raw )], "Embedding Dim": [glove_mgr.dim]})


Zip file already exists, skipping download.


Vocabulary Size  Embedding Dim
0           400000            100

In [ ]:
prep = PrepEngine(
    segment_mode="doc",
    strip_metadata=True,
    drop_stopwords=True,
    min_token_length=3,
    min_token_frequency=5
)

segments, tokens_per_segment = prep.prepare()
vocab_map, freq_df = prep.build_dictionary()
summary_df, top_tokens_df = prep.report(top_n=20)

summary_df


metric  value
0  segments_count  18291
1      vocab_size  27747

In [ ]:
top_tokens_df

term  count
0     like   6529
1      don   6526
2   people   6459
3     just   6178
4     know   5774
5      use   5030
6    think   5004
7     time   4879
8      max   4729
9     does   4510
10     new   4104
11    good   3923
12     edu   3753
13     god   3400
14     way   3397
15    make   3353
16    used   3050
17     say   3017
18   right   3008
19     did   3006

In [ ]:
ng_word_units = list(vocab_map.keys())
covered_count = _np.sum([1 if w in lexicon_raw  else 0 for w in ng_word_units])
coverage_ratio = covered_count / max(1, len(ng_word_units))
oov_words = [w for w in ng_word_units if w not in lexicon_raw ]

report_df = _pd.DataFrame({
    "Newsgroups Vocab Size": [len(ng_word_units)],
    "Covered by GloVe": [covered_count],
    "Coverage %": [round(coverage_ratio*100, 2)],
    "Sample OOV": [oov_words[:25]]
})
report_df


Newsgroups Vocab Size  Covered by GloVe  Coverage %  \
0                  27747             24236       87.35   

                                          Sample OOV  
0  [g9v, b8f, 1d9, 34u, bhj, 75u, 2di, 2tm, xterm...

## <div style="text-align: right; direction: rtl;">همسایه‌های معنایی در فضای Embedding و تحلیل با PCA</div>


<div dir="rtl">

در این بخش،  ابتدا واژه‌های انتخابی خود را از دیکشنری GloVe استخراج کرده و یک نسخه پاک‌سازی‌شده از واژگان ایجاد شد. این پاک‌سازی شامل حذف کلمات کوتاه‌تر از چهار حرف و همچنین حذف کلمات توقف بود. پس از اعمال فیلترهای مذکور، تعداد واژگان به 307314 رسید که 23.17٪ از واژگان اولیه حذف شدند و نمونه‌ای از این واژگان شامل کلماتی مانند `said`, `year`, `people`, `percent`، و `government` می‌باشد.

با استفاده از کلاس **SemanticExplorer**، embeddingهای واژگان انتخاب‌شده به صورت یک ماتریس نرمالیزه ذخیره شد تا امکان محاسبه **cosine similarity** برای یافتن همسایگان معنایی فراهم شود. سپس برای پنج واژه اولیه حاضر در واژگان پاک‌سازی‌شده، نزدیک‌ترین ۱۰ همسایه معنایی آن‌ها استخراج شد و در یک جدول مجزا نمایش داده شد. 


</div>


In [129]:
min_len_threshold = 4
pattern_alpha = r'^[a-z]{%d,}$' % min_len_threshold
words_array = _np.array(list(lexicon_raw.keys()))
words_series = _pd.Series(words_array, name="word")

def preprocess_word(w):
    w_clean = w.lower()
    w_clean = _re.sub(r'[^a-z0-9]', '', w_clean)
    return w_clean

words_series_cleaned = words_series.apply(preprocess_word)
mask_alpha = words_series_cleaned.str.match(pattern_alpha)
mask_stop = ~words_series_cleaned.isin(_STOPWORDS)
mask_final = mask_alpha & mask_stop

clean_words = words_series_cleaned[mask_final].tolist()
lexicon_trimmed = {w: lexicon_raw[w] for w in clean_words if w in lexicon_raw}

stats_df = _pd.DataFrame({
    "raw_vocab": [len(lexicon_raw)],
    "clean_vocab": [len(lexicon_trimmed)],
    "removed_pct": [round((1 - len(lexicon_trimmed)/max(1, len(lexicon_raw))) * 100, 2)],
    "sample_clean_words": [clean_words[:20]]
})
stats_df


raw_vocab  clean_vocab  removed_pct  \
0     400000       307314        23.17   

                                  sample_clean_words  
0  [said, year, people, percent, government, time...

In [130]:
class SemanticExplorer:
    def __init__(self, lexicon_map, k_neighbors: int = 10):
        self.lex = lexicon_map
        self.k = k_neighbors
        self.vocab = list(self.lex.keys())
        self.matrix = _np.vstack([self.lex[w] for w in self.vocab])
        norms = _np.linalg.norm(self.matrix, axis=1, keepdims=True)
        norms[norms == 0] = 1.0
        self.normed = self.matrix / norms
        self.index_map = {w: i for i, w in enumerate(self.vocab)}

    def neighbors_for(self, queries: list):
        rows = []
        present = [q for q in queries if q in self.index_map]
        missing = [q for q in queries if q not in self.index_map]
        for q in present:
            qi = self.index_map[q]
            qv = self.normed[qi]
            sims = self.normed.dot(qv)
            idx_sorted = _np.argsort(sims)[::-1]
            top = [i for i in idx_sorted if i != qi][:self.k]
            for i in top:
                rows.append((q, self.vocab[i], float(sims[i])))
        df_neighbors = _pd.DataFrame(rows, columns=["query_word", "neighbor", "cosine_sim"])
        df_missing = _pd.DataFrame({"missing_query": missing})
        return df_neighbors, df_missing


<div dir="rtl">


#### جدول همسایگان معنایی برای پنج واژه منتخب

به عنوان مثال برای واژه `like` نزدیک‌ترین همسایگان شامل `look`, `things`, `kind`, `come`, و `think` هستند. مقادیر similarity برای این همسایگان بین 0.7617 تا 0.8113 قرار دارند. برای واژه `people` همسایگان شامل `residents`, `families`, `lives`, `children` و `citizens` هستند و similarityهای آن‌ها بین 0.7165 تا 0.7647 است. این مقادیر نشان می‌دهند که کلمات انتخاب‌شده از نظر معنایی به واژه‌های اصلی نزدیک بوده و غالباً از نظر موضوعی با آن‌ها مرتبط هستند. 

#### تحلیل نوع روابط معنایی

همسایگان معنایی می‌توانند روابط متنوعی داشته باشند:
- **مترادف‌ها:** مانند `think` و `know` که در بسیاری از متون با هم جایگزین‌پذیر هستند.
- **مرتبط موضوعی:** مانند `people` و `citizens` که در زمینه‌های اجتماعی و جمعیتی با هم مرتبطند.
- **هم‌آیند (collocational):** کلماتی که غالباً در کنار هم ظاهر می‌شوند مانند `just` و `going`.

در مقایسه با همسایه‌های paradigmatic و syntagmatic که در بخش اول بررسی شده بود، مشاهده می‌کنیم که همسایه‌های paradigmatic بیشتر مترادف یا مشابه معنایی مستقیم هستند، در حالی که همسایه‌های syntagmatic، ترکیب‌های زبانی یا هم‌آیند را نشان می‌دهند. در نتایج ما، ترکیبی از این روابط در همسایه‌های استخراج‌شده دیده می‌شود.


</div>


In [126]:
all_candidate_words = [w for w in vocab_map.keys() if w in lexicon_trimmed]
analysis_words = all_candidate_words[:5]  

explorer = SemanticExplorer(lexicon_trimmed, k_neighbors=10)
combined_neighbors_df, missing_queries_df = explorer.neighbors_for(analysis_words)


In [100]:
fig_neighbors_table = _make_subplots(
    rows=1, cols=min(len(analysis_words), 5),
    subplot_titles=analysis_words[:5],
    specs=[[{"type": "table"}]*min(len(analysis_words), 5)]
)

for i, w in enumerate(analysis_words[:5]):
    df_tmp = combined_neighbors_df[combined_neighbors_df["query_word"] == w]
    if df_tmp.empty:
        continue
    fig_neighbors_table.add_trace(_go.Table(
        header=dict(values=["Neighbor", "Cosine Similarity"],
                    fill_color='lightseagreen', align='left'),
        cells=dict(values=[
            df_tmp["neighbor"],
            df_tmp["cosine_sim"].round(4)
        ], fill_color='azure', align='left')
    ), row=1, col=i+1)

fig_neighbors_table.update_layout(
    width=350*min(len(analysis_words), 5),
    height=400,
    title_text="Top Semantic Neighbors per Selected Words",
    margin=dict(l=20, r=20, t=60, b=20)
)
fig_neighbors_table.show()


<div dir="rtl">

#### تحلیل PCA و کاهش ابعاد با رسم محیط خوشه‌ها

در تحلیل PCA که انجام شد، embeddingهای واژه‌های اصلی و همسایه‌هایشان به فضای دوبعدی کاهش یافتند و برای هر واژه اصلی، با استفاده از **Convex Hull** یک محیط رنگی دور خوشه رسم شد. واژه‌های اصلی با رنگ قرمز و همسایه‌ها با رنگ آبی مشخص شدند تا تفکیک واضحی ایجاد شود.

با این حال، مشاهده می‌کنیم که محیط‌های خوشه‌ها **با هم همپوشانی دارند**. دلیل این موضوع این است که برخی همسایه‌ها ممکن است به بیش از یک واژه اصلی نزدیک باشند و به همین دلیل در فضای PCA در نزدیکی چند خوشه قرار می‌گیرند. علاوه بر این، PCA با کاهش ابعاد به دو بعد، ممکن است فاصله‌های واقعی چندبعدی بین کلمات را به صورت فشرده و نزدیک در یک صفحه دوبعدی نمایش دهد، که باعث همپوشانی محیط‌ها می‌شود.

 این مشکل معمولاً در embeddingهای معنایی با تعداد زیاد همسایه‌ها و کاهش ابعاد به ۲ بعد طبیعی است. برای کاهش همپوشانی می‌توان تعداد همسایه‌ها را کم کرد، یا از روش‌های غیرخطی مانند **t-SNE** یا **UMAP** استفاده نمود تا خوشه‌ها در فضای دوبعدی واضح‌تر و با پراکندگی واقعی‌تر نمایش داده شوند.

</div>


In [ ]:
class EmbeddingVisualizer:
    def __init__(self, embedding_dict, neighbors_dict):
        self.embeddings = embedding_dict
        self.neighbors = neighbors_dict
        self.points = []
        self.labels = []
        self.colors = []

    def prepare_plot_data(self):
        for tgt, neigh_list in self.neighbors.items():
            self.points.append(self.embeddings[tgt])
            self.labels.append(tgt)
            self.colors.append('red')
            for nb_word, _ in neigh_list:
                self.points.append(self.embeddings[nb_word])
                self.labels.append(nb_word)
                self.colors.append('blue')
        self.points = _np.array(self.points)
        return self.points, self.labels, self.colors

    def reduce_dimensionality(self, n_components=2):
        from sklearn.preprocessing import StandardScaler
        from sklearn.decomposition import PCA
        scaler = _Scaler()
        scaled = scaler.fit_transform(self.points)
        pca = _PCA(n_components=n_components)
        reduced = pca.fit_transform(scaled)
        return reduced


In [125]:
word_neighbors = {}
for w in analysis_words:
    tmp = combined_neighbors_df[combined_neighbors_df["query_word"] == w]
    word_neighbors[w] = list(zip(tmp["neighbor"], tmp["cosine_sim"]))

plotter = EmbeddingVisualizer(lexicon_trimmed, word_neighbors)
pts, labels, colors = plotter.prepare_plot_data()
pca_result = plotter.reduce_dimensionality()
plot_df = _pd.DataFrame(pca_result, columns=["PC1", "PC2"], index=labels)
plot_df['Color'] = colors



In [121]:
from scipy.spatial import ConvexHull

fig_group = _go.Figure()

for i, grp in enumerate(analysis_words):
    df_grp = plot_df[plot_df["Group"] == grp].copy()
    df_grp["PlotColor"] = ['red' if idx == grp else 'blue' for idx in df_grp.index]
    marker_sizes = [15 if c=='red' else 10 for c in df_grp["PlotColor"]]

    fig_group.add_trace(
        _go.Scatter(
            x=df_grp["PC1"],
            y=df_grp["PC2"],
            mode='markers+text',
            text=df_grp.index,
            textposition='top center',
            marker=dict(color=df_grp["PlotColor"], size=marker_sizes),
            name=grp
        )
    )

    if len(df_grp) >= 3:
        points = df_grp[["PC1", "PC2"]].values
        try:
            hull = ConvexHull(points, qhull_options="QJ")
            hull_points = points[hull.vertices]
            hull_points = _np.vstack([hull_points, hull_points[0]])
            fig_group.add_trace(
                _go.Scatter(
                    x=hull_points[:,0],
                    y=hull_points[:,1],
                    mode='lines',
                    line=dict(color=base_colors[i % len(base_colors)], width=2),
                    fill='toself',
                    opacity=0.2,
                    showlegend=False
                )
            )
        except:
            continue

fig_group.update_layout(
    title="Word Groups with Semantic Neighbors (PCA 2D)",
    width=1200,
    height=900
)
fig_group.show()


In [123]:
from scipy.spatial import ConvexHull

fig = _make_subplots(
    rows=1, cols=len(analysis_words),
    subplot_titles=analysis_words,
    specs=[[{"type": "scatter"}]*len(analysis_words)]
)

base_colors = _px.colors.qualitative.Dark24

for i, word in enumerate(analysis_words):
    word_group = [word] + [nb for nb, _ in word_neighbors[word]]
    df_group = plot_df.loc[word_group].copy()
    df_group["PlotColor"] = ['red' if w==word else 'blue' for w in df_group.index]
    df_group["MarkerSize"] = [15 if c=='red' else 10 for c in df_group["PlotColor"]]

    fig.add_trace(
        _go.Scatter(
            x=df_group["PC1"],
            y=df_group["PC2"],
            mode='markers+text',
            text=df_group.index,
            textposition='top center',
            marker=dict(color=df_group['PlotColor'], size=df_group['MarkerSize'])
        ),
        row=1, col=i+1
    )

    if len(df_group) >= 3:
        points = df_group[["PC1", "PC2"]].values
        try:
            hull = ConvexHull(points, qhull_options="QJ")
            hull_points = points[hull.vertices]
            hull_points = _np.vstack([hull_points, hull_points[0]])
            fig.add_trace(
                _go.Scatter(
                    x=hull_points[:,0],
                    y=hull_points[:,1],
                    mode='lines',
                    line=dict(color=base_colors[i % len(base_colors)], width=2),
                    fill='toself',
                    opacity=0.2,
                    showlegend=False
                ),
                row=1, col=i+1
            )
        except:
            continue

fig.update_layout(
    title="2D PCA Visualization of Each Word with Semantic Neighbors and Convex Hulls",
    showlegend=False,
    height=700,
    width=300*len(analysis_words)
)
fig.show()


## <div style="text-align: right; direction: rtl;">ساخت Query Embedding و Document Embedding برای Cranfield و تحلیل</div>



<div dir="rtl">

## شرح پیاده‌سازی و منطق روش
در این بخش هدف وارد کردن embeddingهای مبتنی بر GloVe به فضای مجموعه Cranfield و ارزیابی رفتار آن‌ها در وظیفهٔ سادهٔ مقایسهٔ پرسش-سند بود. ابتدا داده‌ها با یک بارخوانی از فایل‌های استاندارد Cranfield بارگذاری شدند؛ ۱۴۰۰ سند و ۲۲۵ پرسش شناسایی شد (خروجی: Loaded 1400 documents and 225 queries). سپس متن‌ها به روش زیر پیش‌پردازش شدند: همگی به حروف کوچک تبدیل شدند و نویسه‌های غیرحروفی حذف شدند. برای هر سند و هر پرسش، میانگین وکتورهای کلماتی که در واژگان GloVe وجود داشتند به عنوان نمایندهٔ آن متن محاسبه شد (روش میانگین بردارها).

برای هر زوج (query, document) که در qrel برچسب وجود داشت، مقدار شباهت زاویه‌ای (cosine similarity) بین embedding پرسش و embedding سند محاسبه و ذخیره شد. 
در نهایت داده‌های qrel به سه مجموعهٔ آموزش، اعتبارسنجی و تست تقسیم شدند (تعداد پرسش‌ها: Train = 135، Val = 45، Test = 45) و برای زوج‌های موجود در هر مجموعه، ویژگی «Embedding Similarity» محاسبه و در خروجی نگهداری شد.

در طول پیاده‌سازی چند تصمیم طراحی گرفته شد که در گزارش اثرشان را توضیح می‌دهم:
- استفاده از میانگین سادهٔ بردارها (بدون وزن‌دهی TF–IDF) تا پیوند روش را با پیوستگی آماری واژگان حفظ کنیم.
- حذف نویسه‌های غیرالفبایی قبل از نگاشت به واژگان GloVe تا همپوشانی‌های نویزی کاهش یابد.
- همواره کلیدهای id (query_id و doc_id) را به رشته تبدیل و یکسان‌سازی کردم تا همخوانی بین qrel و دیکشنری embeddingها تضمین شود.


</div>


In [16]:
class CranfieldLoader:
    def __init__(self, doc_path, qry_path):
        self.doc_path = doc_path
        self.qry_path = qry_path

    def load(self):
        with open(self.doc_path, "r", encoding="utf-8") as f:
            raw_docs = f.readlines()
        with open(self.qry_path, "r", encoding="utf-8") as f:
            raw_qrys = f.readlines()

        docs_dict = {}
        qrys_dict = {}

        current_id = None
        buffer_text = []
        for ln in raw_docs:
            if ln.startswith(".I"):
                if current_id is not None:
                    docs_dict[current_id] = " ".join(buffer_text).strip()
                current_id = ln.strip().split()[1]
                buffer_text = []
            elif not ln.startswith(".W"):
                buffer_text.append(ln.strip())
        if current_id is not None:
            docs_dict[current_id] = " ".join(buffer_text).strip()

        current_id = None
        buffer_text = []
        for ln in raw_qrys:
            if ln.startswith(".I"):
                if current_id is not None:
                    qrys_dict[current_id] = " ".join(buffer_text).strip()
                current_id = ln.strip().split()[1]
                buffer_text = []
            elif not ln.startswith(".W"):
                buffer_text.append(ln.strip())
        if current_id is not None:
            qrys_dict[current_id] = " ".join(buffer_text).strip()

        return docs_dict, qrys_dict


In [17]:
doc_file = "cran.all.1400"
qry_file = "cran.qry"
loader = CranfieldLoader(doc_file, qry_file)
documents, queries = loader.load()

print(f"Loaded {len(documents)} documents and {len(queries)} queries.\n")

print("=== Sample Documents ===")
for idx, (doc_id, doc_text) in enumerate(list(documents.items())[:5], 1):
    snippet = " ".join(doc_text.split()[:40])
    print(f"[Doc {doc_id}] {snippet} ...\n")

print("=== Sample Queries ===")
for idx, (query_id, query_text) in enumerate(list(queries.items())[:5], 1):
    snippet = " ".join(query_text.split()[:20])
    print(f"[Query {query_id}] {snippet} ...\n")


Loaded 1400 documents and 225 queries.

=== Sample Documents ===
[Doc 1] .T experimental investigation of the aerodynamics of a wing in a slipstream . .A brenckman,m. .B j. ae. scs. 25, 1958, 324. experimental investigation of the aerodynamics of a wing in a slipstream . an experimental study of a wing ...

[Doc 2] .T simple shear flow past a flat plate in an incompressible fluid of small viscosity . .A ting-yili .B department of aeronautical engineering, rensselaer polytechnic institute troy, n.y. simple shear flow past a flat plate in an incompressible fluid of ...

[Doc 3] .T the boundary layer in simple shear flow past a flat plate . .A m. b. glauert .B department of mathematics, university of manchester, manchester, england the boundary layer in simple shear flow past a flat plate . the boundary-layer ...

[Doc 4] .T approximate solutions of the incompressible laminar boundary layer equations for a plate in shear flow . .A yen,k.t. .B j. ae. scs. 22, 1955, 728. approximate solutio

In [21]:
class TextEmbedder:
    def __init__(self, embedding_dict, vector_dim=100):
        self.lookup = embedding_dict
        self.dim = vector_dim

    def preprocess(self, text):
        clean_text = text.lower()
        clean_text = _re.sub(r'[^a-z0-9\s]', '', clean_text)
        return clean_text

    def embed(self, text):
        words = text.split()
        vecs = _np.array([self.lookup[w] for w in words if w in self.lookup])
        if vecs.shape[0] == 0:
            return _np.zeros(self.dim)
        return _np.mean(vecs, axis=0)

processor = TextEmbedder(lexicon_raw, vector_dim=100)

processed_docs = {did: processor.preprocess(dtxt) for did, dtxt in documents.items()}
processed_qrys = {qid: processor.preprocess(qtxt) for qid, qtxt in queries.items()}

doc_embeddings = {did: processor.embed(dtxt) for did, dtxt in processed_docs.items()}
qry_embeddings = {qid: processor.embed(qtxt) for qid, qtxt in processed_qrys.items()}

_pd.DataFrame({
    "Document ID": list(doc_embeddings.keys())[:3],
    "Sample Embedding": [doc_embeddings[k][:5] for k in list(doc_embeddings.keys())[:3]]
})



Document ID                                   Sample Embedding
0           1  [-0.14707881, 0.04410789, 0.17524439, -0.02527...
1           2  [-0.19493118, 0.11043306, 0.24273723, -0.04166...
2           3  [-0.2503224, 0.12778424, 0.14799088, 0.0429387...

In [22]:
with open("cranqrel", "r", encoding="utf-8") as f:
    qrel_lines = f.readlines()

qrel_records = []
for line in qrel_lines:
    parts = line.strip().split()
    if len(parts) == 3:
        qid, did, score = map(int, parts)
        qrel_records.append((qid, did, score))

qrel_df = _pd.DataFrame(qrel_records, columns=["query_id", "doc_id", "score"])

train_queries, temp_queries = _split(qrel_df['query_id'].unique(), test_size=0.4, random_state=42)
val_queries, test_queries = _split(temp_queries, test_size=0.5, random_state=42)

train_data = qrel_df[qrel_df['query_id'].isin(train_queries)].reset_index(drop=True)
val_data = qrel_df[qrel_df['query_id'].isin(val_queries)].reset_index(drop=True)
test_data = qrel_df[qrel_df['query_id'].isin(test_queries)].reset_index(drop=True)

print(f"Train queries: {len(train_queries)}, Val queries: {len(val_queries)}, Test queries: {len(test_queries)}")
print(f"Train pairs: {len(train_data)}, Val pairs: {len(val_data)}, Test pairs: {len(test_data)}")


Train queries: 135, Val queries: 45, Test queries: 45
Train pairs: 1152, Val pairs: 345, Test pairs: 340


In [23]:
def cosine_similarity_manual(vec1, vec2):
    dot_product = _np.dot(vec1, vec2)
    norm1 = _np.linalg.norm(vec1)
    norm2 = _np.linalg.norm(vec2)
    if norm1 == 0 or norm2 == 0:
        return 0.0
    return dot_product / (norm1 * norm2)


In [24]:
class QueryDocFeatureBuilder:
    def __init__(self, doc_embeds, qry_embeds, qrel_df):
        self.doc_embeds = {str(k).strip(): v for k, v in doc_embeds.items()}
        self.qry_embeds = {str(k).strip(): v for k, v in qry_embeds.items()}
        
        self.qrel = qrel_df.copy()
        self.qrel['query_id'] = self.qrel['query_id'].astype(str).str.strip()
        self.qrel['doc_id'] = self.qrel['doc_id'].astype(str).str.strip()

    def build_embedding_features(self):
        feature_records = []

        for _, row in _tqdm(self.qrel.iterrows(),total=len(self.qrel),desc="Building Embedding Features"):

            qid = row['query_id']
            did = row['doc_id']

            if qid not in self.qry_embeds or did not in self.doc_embeds:
                continue

            sim_score = cosine_similarity_manual(
                self.qry_embeds[qid],
                self.doc_embeds[did]
            )

            feature_records.append(
                (qid, did, row['score'], sim_score)
            )

        return _pd.DataFrame(
            feature_records,
            columns=["Query ID", "Document ID", "Relevance", "Embedding Similarity"]
        )


In [25]:
feature_builder_train = QueryDocFeatureBuilder(doc_embeddings, qry_embeddings, train_data)
train_features = feature_builder_train.build_embedding_features()

feature_builder_val = QueryDocFeatureBuilder(doc_embeddings, qry_embeddings, val_data)
val_features = feature_builder_val.build_embedding_features()

feature_builder_test = QueryDocFeatureBuilder(doc_embeddings, qry_embeddings, test_data)
test_features = feature_builder_test.build_embedding_features()


Building Embedding Features: 100%|██████████| 340/340 [00:00<00:00, 32417.90it/s]


In [26]:
def show_summary(name, df):
    print(f"\n===== {name} =====")
    print(f"Total pairs: {len(df)}")
    print(f"Mean similarity: {df['Embedding Similarity'].mean():.4f}")
    print(f"Min similarity:  {df['Embedding Similarity'].min():.4f}")
    print(f"Max similarity:  {df['Embedding Similarity'].max():.4f}")

show_summary("TRAIN", train_features)
show_summary("Val", val_features)
show_summary("TEST", test_features)



===== TRAIN =====
Total pairs: 480
Mean similarity: 0.9263
Min similarity:  0.7024
Max similarity:  0.9798

===== Val =====
Total pairs: 127
Mean similarity: 0.9088
Min similarity:  0.6758
Max similarity:  0.9800

===== TEST =====
Total pairs: 136
Mean similarity: 0.8901
Min similarity:  0.6907
Max similarity:  0.9757


<div dir="rtl">

تعداد زوج‌های محاسبه‌شده در هر مجموعه:

- TRAIN: 480 زوج، میانگین similarity = 0.9263، کمینه = 0.7024، بیشینه = 0.9798  
- DEV: 127 زوج، میانگین similarity = 0.9088، کمینه = 0.6758، بیشینه = 0.9800  
- TEST: 136 زوج، میانگین similarity = 0.8901، کمینه = 0.6907، بیشینه = 0.9757

نمونه‌ای از جدول نتایج:

| Query ID | Query Text (برش) | Document ID | Document Text (برش) | Relevance | Embedding Similarity |
|---:|---|---:|---|---:|---:|
| 100 | how much is known about boundary layer flows a... | 821 | .T inelastic column theory ... | 2 | 0.9024 |
| 100 | how much is known about boundary layer flows a... | 760 | .T inelastic buckling ... | -1 | 0.8957 |
| 101 | is there any simple, but practical, method f... | 818 | .T a quantitative comparison ... | 2 | 0.9526 |
| 101 | is there any simple, but practical, method f... | 760 | .T inelastic buckling ... | -1 | 0.9547 |

در این نمونه‌ها، اسناد مرتبط معمولاً شباهت بالاتری دارند، اما گاهی اسناد غیرمرتبط نیز similarity بالایی نشان می‌دهند.

## تحلیل نتایج
چند نکته دربارهٔ رفتار مشاهده‌شده:

1. **اثر میانگین بردارها و واژگان عمومی**  
   کلمات پرتکرار و عمومی در متن، تأثیر زیادی روی بردار میانگین دارند. بنابراین دو سند با موضوع متفاوت اما واژگان عمومی مشابه، similarity بالایی نشان می‌دهند.

2. **کلمات خارج از واژگان (OOV)**  
   بعضی کلمات در GloVe وجود ندارند و بردار آن‌ها صفر است؛ این موضوع باعث می‌شود تفاوت بین اسناد مرتبط و غیرمرتبط کاهش یابد.

3. **محدودیت Cosine**  
   cosine similarity فقط زاویه بین بردارها را می‌سنجد و تفاوت‌های معنایی کوچک را در نظر نمی‌گیرد؛ بنابراین مقادیر اغلب بالا و نزدیک به هم هستند.

4. **نمونه خطاها**  
   بعضی اسناد غیرمرتبط با similarity بالا وجود دارند، زیرا کلمات کلیدی مشترکی با پرسش دارند (مثل "buckling" یا "boundary")، حتی اگر موضوع اصلی مرتبط نباشد.

روش میانگین بردارهای GloVe برای تحلیل سریع مناسب است، اما برای بهبود دقت:

- استفاده از وزن‌دهی TF–IDF برای برجسته کردن کلمات مهم  
- حذف یا کاهش تأثیر واژگان پرتکرار  
- استفاده از مدل‌های پیشرفته‌تر مثل BERT  
- بررسی خطاها برای پیدا کردن الگوهای اشتباه


</div>


In [203]:
class PairSampler:
    def __init__(self, qrel_table, pos_marks=(3, 4), neg_mark=-1, per_class=2):
        tbl = qrel_table.copy()
        tbl["query_id"] = tbl["query_id"].astype(str)
        tbl["doc_id"] = tbl["doc_id"].astype(str)
        self.tbl = tbl
        self.pos_marks = pos_marks
        self.neg_mark = neg_mark
        self.per_class = per_class

    def sample(self, qid_subset):
        qid_subset = [str(q) for q in qid_subset]
        picked = []
        for q in qid_subset:
            block = self.tbl[self.tbl["query_id"] == q]
            pos = block[block["score"].isin(self.pos_marks)].head(self.per_class)
            neg = block[block["score"] == self.neg_mark].head(self.per_class)
            picked.append(_pd.concat([pos, neg]))
        return _pd.concat(picked).reset_index(drop=True)


chosen_queries = list(train_data["query_id"].astype(str).unique()[:3])
sampler = PairSampler(train_data, pos_marks=(2, 3), neg_mark=-1, per_class=2)
sample_pairs = sampler.sample(chosen_queries)
sample_pairs.head()


query_id doc_id  score
0        1    184      2
1        1     29      2
2        1    486     -1
3        2     15      2
4        2    184      2

In [216]:
class SimilarityTableBuilder:
    def __init__(self, doc_vecs, qry_vecs, docs_text, qrys_text):
        self.dv = {str(k).strip(): v for k, v in doc_vecs.items()}
        self.qv = {str(k).strip(): v for k, v in qry_vecs.items()}
        self.docs = {str(k).strip(): v for k, v in docs_text.items()}
        self.qrys = {str(k).strip(): v for k, v in qrys_text.items()}

    def assemble_with_nonrel(self, qrel_df, top_k=4):
        results = []
        for qid in qrel_df["query_id"].unique():
            qid_str = str(qid).strip()
            if qid_str not in self.qv:
                continue
            q_emb = self.qv[qid_str]
            
            rel_docs = qrel_df[(qrel_df["query_id"] == qid) & (qrel_df["score"] > 0)].head(top_k)
            nonrel_docs = qrel_df[(qrel_df["query_id"] == qid) & (qrel_df["score"] <= 0)].head(top_k)
            
            selected_docs = _pd.concat([rel_docs, nonrel_docs])
            
            for _, row in selected_docs.iterrows():
                did_str = str(row["doc_id"]).strip()
                if did_str not in self.dv:
                    continue
                d_emb = self.dv[did_str]
                sim = _np.dot(q_emb, d_emb) / (_np.linalg.norm(q_emb) * _np.linalg.norm(d_emb) + 1e-9)
                results.append({
                    "Query ID": qid_str,
                    "Query Text": self.qrys.get(qid_str, "")[:150] + "...",
                    "Document ID": did_str,
                    "Document Text": self.docs.get(did_str, "")[:150] + "...",
                    "Relevance": row["score"],
                    "Embedding Similarity": sim
                })
        
        return _pd.DataFrame(results)


builder = SimilarityTableBuilder(doc_embeddings, qry_embeddings, documents, queries)
analysis_table = builder.assemble_with_nonrel(qrel_df)
analysis_table.head(10)


Query ID                                         Query Text Document ID  \
0      100  how much is known about boundary layer flows a...         821   
1      100  how much is known about boundary layer flows a...         822   
2      100  how much is known about boundary layer flows a...         824   
3      100  how much is known about boundary layer flows a...         820   
4      100  how much is known about boundary layer flows a...         760   
5      101  is there any simple,  but practical,  method f...         817   
6      101  is there any simple,  but practical,  method f...         818   
7      101  is there any simple,  but practical,  method f...         819   
8      101  is there any simple,  but practical,  method f...         820   
9      101  is there any simple,  but practical,  method f...         760   

                                       Document Text  Relevance  \
0  .T inelastic column theory . .A shanley,f.r. ....          2   
1  .T effects of imperfections on buckling of thi...          2   
2  .T on the concept of stability of inelastic sy...          2   
3  .T theories of plastic buckling . .A batdorf,s...          3   
4  .T inelastic buckling of initially imperfect c...         -1   
5  .T loading paths and the incremental stress la...          2   
6  .T a quantitative comparison of flow and defor...          2   
7  .T stresses in the plastic range around a norm...          2   
8  .T theories of plastic buckling . .A batdorf,s...          3   
9  .T inelastic buckling of initially imperfect c...         -1   

   Embedding Similarity  
0              0.902441  
1              0.918053  
2              0.903624  
3              0.906521  
4              0.895733  
5              0.943632  
6              0.952616  
7              0.944532  
8              0.955881  
9              0.954703

# <div style="text-align: center; direction: rtl;"><h1 align="center" style="font-size: 24px; padding: 20px;">━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br>سوال سوم - پیاده‌سازی مدل‌های LEARNING TO RANK   <br>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</h1></div>


## <div style="text-align: right; direction: rtl;">مجموعه‌داده</div>


In [42]:
import tarfile as _tar

cran_url = "https://ir.dcs.gla.ac.uk/resources/test_collections/cran/cran.tar.gz"
cran_archive_path = "cran.tar.gz"

_urlreq.urlretrieve(cran_url, cran_archive_path)

with _tar.open(cran_archive_path, "r:gz") as archive:
    archive.extractall("cran_dataset")
    cran_files = {member.name: member for member in archive.getmembers() if member.isfile()}

cran_files.keys()


dict_keys(['cran.all.1400', 'cran.qry', 'cranqrel', 'cranqrel.readme'])

## <div style="text-align: right; direction: rtl;">ساخت Feature Vector برای هر زوج (Query, Document)</div>


<div dir="rtl">

## پیش‌پردازش اسناد و پرسش‌ها

برای آماده‌سازی داده‌ها، کلاس `CranfieldPreprocessor` طراحی شد. این کلاس وظیفه داشت تا:

1. اسناد و پرسش‌ها را به صورت **Text** بارگذاری کند.
2. متن‌ها را به صورت **lowercase** تبدیل و کاراکترهای غیرحروفی را حذف نماید.
3. کلمات توقف (Stopwords) را حذف کرده و تنها کلمات معنی‌دار با طول بیش از یک کاراکتر نگه داشته شوند.
4. تعداد کلمات هر سند و پرسش محاسبه شود.

با اجرای این پیش‌پردازش، ما یک **DataFrame** برای اسناد و پرسش‌ها دریافت کردیم که به ترتیب شامل ستون‌های `DocID`, `Text`, `WordCount` و `QueryID`, `QueryText`, `WordCount` هستند. برای نمونه، پنج ردیف اول هر مجموعه داده به شرح زیر است:

| DocID | Text | WordCount |
|-------|------|-----------|
| 1 | experimental investigation aerodynamics wing s... | 78 |
| 2 | simple shear flow past flat plate incompressib... | 132 |
| 3 | boundary layer simple shear flow past flat pla... | 32 |
| 4 | approximate solutions incompressible laminar b... | 56 |
| 5 | dimensional transient heat conduction double l... | 51 |

| QueryID | QueryText | WordCount |
|---------|-----------|-----------|
| 001 | similarity laws obeyed constructing aeroelasti... | 10 |
| 002 | structural aeroelastic problems associated fli... | 8 |
| 004 | problems heat conduction composite slabs solve... | 7 |
| 008 | criterion developed empirically validity flow ... | 17 |
| 009 | chemical kinetic applicable hypersonic aerodyn... | 6 |


## ساخت بردار ویژگی‌ها برای هر زوج (Query, Document)

برای استخراج ویژگی‌ها از هر **Query-Document Pair**، کلاس `AdvancedFeatureBuilder` طراحی شد که ویژگی‌های زیر را محاسبه می‌کند:

1. **TF-IDF Cosine Similarity**  

این ویژگی نشان‌دهنده میزان همپوشانی کلمات مهم بین پرسش و سند است و برای رتبه‌بندی اهمیت دارد.

2. **Embedding Cosine Similarity**  

این ویژگی معنای مفهومی متن‌ها را اندازه می‌گیرد و می‌تواند ارتباط معنایی نهفته بین پرسش و سند را شبیه‌سازی کند. برای محاسبه embeddingها از مدل `SentenceTransformer('all-MiniLM-L6-v2')` استفاده شد.

3. **Common Word Ratio**  

این ویژگی نشان‌دهنده نسبت کلمات مشترک بین پرسش و سند است.

4. **Logarithmic Length**  

طول پرسش و سند با تابع لگاریتم گرفته شده است تا مقیاس طول‌ها نرم شود و تاثیر طول‌های بسیار بزرگ کاهش یابد.

5. **Mean IDF**  

این ویژگی اهمیت نسبی کلمات در پرسش و سند را اندازه می‌گیرد؛ کلمات کمتر رایج دارای IDF بالاتر هستند.

6. **Relevance Score**  
از فایل `cranqrel` گرفته شده و نشان‌دهنده میزان ارتباط سند با پرسش است.



### تقسیم‌بندی داده‌ها

برای اطمینان از تعادل مجموعه داده، فقط **Query**هایی که relevance مشخص دارند در نظر گرفته شدند. سپس تقسیم‌بندی به صورت زیر انجام شد:

* **Train**: ۷۰٪ پرسش‌ها → ۶۵ پرسش، ۴۴۳ جفت query-document
* **Validation**: ۱۵٪ پرسش‌ها → ۱۴ پرسش، ۱۳۴ جفت query-document
* **Test**: ۱۵٪ پرسش‌ها → ۱۵ پرسش، ۱۶۶ جفت query-document



### نمونه خروجی بردار ویژگی‌ها

#### Train Set
| QID | DID | TFIDF_Cos | CommonWord_Ratio | Log_QLen | Log_DLen | MeanIDF_Q | MeanIDF_D | Embedding_Cos | Relevance |
|-----|-----|------------|-----------------|----------|----------|------------|------------|----------------|-----------|
| 100 | 821 | 0.000000   | 0.000000        | 2.079442 | 3.931826 | 3.303808   | 4.749533   | 0.164597       | 2         |
| 100 | 822 | 0.093517   | 0.011111        | 2.079442 | 4.804021 | 3.303808   | 4.517111   | 0.213298       | 2         |

#### Validation Set
| QID | DID | TFIDF_Cos | CommonWord_Ratio | Log_QLen | Log_DLen | MeanIDF_Q | MeanIDF_D | Embedding_Cos | Relevance |
|-----|-----|------------|-----------------|----------|----------|------------|------------|----------------|-----------|
| 182 | 685 | 0.012096   | 0.008850        | 3.044522 | 5.192957 | 3.798364   | 4.135302   | 0.374610       | 1         |

#### Test Set
| QID | DID | TFIDF_Cos | CommonWord_Ratio | Log_QLen | Log_DLen | MeanIDF_Q | MeanIDF_D | Embedding_Cos | Relevance |
|-----|-----|------------|-----------------|----------|----------|------------|------------|----------------|-----------|
| 208 | 163 | 0.012855   | 0.012195        | 2.302585 | 5.484797 | 3.875226   | 5.109059   | 0.057192       | 3         |



1. **TF-IDF Cosine**: مقادیر نزدیک به صفر برای بسیاری از جفت‌ها مشاهده شد. این موضوع نشان می‌دهد که بیشتر پرسش‌ها و اسناد دارای کلمات مشترک کمی هستند، ولی جفت‌هایی با TF-IDF بالا احتمالاً اسناد بسیار مرتبط هستند.

2. **Embedding Cosine**: حتی در جفت‌هایی که TF-IDF کم است، embedding-based similarity مقادیر مثبتی دارد، که نشان‌دهنده ارتباط معنایی بین کلمات است.

3. **طول و Log Length**: پرسش‌ها معمولاً کوتاه‌تر از اسناد هستند و Log Length تفاوت اندازه را کاهش می‌دهد.

4. **Mean IDF**: مقادیر IDF نشان می‌دهند که پرسش‌ها حاوی کلمات خاص‌تر هستند و سندهایی با کلمات کمتر رایج، احتمال مرتبط بودن بیشتری دارند.

5. **توزیع داده‌ها**: با ۶۵ پرسش در مجموعه train و ۴۴۳ جفت، هر پرسش به طور متوسط با چند سند مرتبط شده است، که به مدل برای یادگیری الگوهای مرتبط کمک می‌کند.


</div>


In [73]:
class CranfieldPreprocessor:
    def __init__(self, data_dir):
        self.data_dir = data_dir
        self.documents = {}
        self.queries = {}
        self.relevances = _pd.DataFrame()
    
    def clean_text(self, text):
        text = text.lower()
        text = _re.sub(r"[^a-z\s]", " ", text)
        tokens = [w for w in text.split() if w not in _STOPWORDS and len(w) > 1]
        return " ".join(tokens)
    
    def load_documents(self, file_name="cran.all.1400"):
        path = _os.path.join(self.data_dir, file_name)
        with open(path, "r") as f:
            lines = f.readlines()
        doc_id, doc_lines = None, []
        for line in lines:
            line = line.strip()
            if line.startswith(".I"):
                if doc_id is not None:
                    text = self.clean_text(" ".join(doc_lines))
                    self.documents[doc_id] = text
                doc_id = line[2:].strip()
                doc_lines = []
            elif line and not line.startswith((".T", ".A", ".B", ".W")):
                doc_lines.append(line)
        if doc_id is not None:
            text = self.clean_text(" ".join(doc_lines))
            self.documents[doc_id] = text
        df = _pd.DataFrame(list(self.documents.items()), columns=["DocID", "Text"])
        df["WordCount"] = df["Text"].apply(lambda x: len(x.split()))
        return df
    
    def load_queries(self, file_name="cran.qry"):
        path = _os.path.join(self.data_dir, file_name)
        with open(path, "r") as f:
            lines = f.readlines()
        q_id, q_lines = None, []
        for line in lines:
            line = line.strip()
            if line.startswith(".I"):
                if q_id is not None:
                    text = self.clean_text(" ".join(q_lines))
                    self.queries[q_id] = text
                q_id = line[2:].strip()
                q_lines = []
            elif line and not line.startswith(".W"):
                q_lines.append(line)
        if q_id is not None:
            text = self.clean_text(" ".join(q_lines))
            self.queries[q_id] = text
        df = _pd.DataFrame(list(self.queries.items()), columns=["QueryID", "QueryText"])
        df["WordCount"] = df["QueryText"].apply(lambda x: len(x.split()))
        return df
    
    def load_relevance(self, file_name="cranqrel"):
        path = _os.path.join(self.data_dir, file_name)
        rels = _pd.read_csv(path, sep="\s+", header=None, names=["QueryID", "DocID", "Score"])
        self.relevances = rels
        return rels

preprocessor = CranfieldPreprocessor("cran_dataset")
docs_df = preprocessor.load_documents()
queries_df = preprocessor.load_queries()
qrels_df = preprocessor.load_relevance()

docs_df.head(5), queries_df.head(5), qrels_df.head(5)


(  DocID                                               Text  WordCount
 0     1  experimental investigation aerodynamics wing s...         78
 1     2  simple shear flow past flat plate incompressib...        132
 2     3  boundary layer simple shear flow past flat pla...         32
 3     4  approximate solutions incompressible laminar b...         56
 4     5  dimensional transient heat conduction double l...         51,
   QueryID                                          QueryText  WordCount
 0     001  similarity laws obeyed constructing aeroelasti...         10
 1     002  structural aeroelastic problems associated fli...          8
 2     004  problems heat conduction composite slabs solve...          7
 3     008  criterion developed empirically validity flow ...         17
 4     009  chemical kinetic applicable hypersonic aerodyn...          6,
    QueryID  DocID  Score
 0        1    184      2
 1        1     29      2
 2        1     31      2
 3        1     12      3
 4  

In [69]:
class AdvancedFeatureBuilder:
    def __init__(self, docs, queries, relevances, query_embeddings=None, doc_embeddings=None):
        self.docs = docs.set_index("DocID")["Text"].to_dict()
        self.queries = queries.set_index("QueryID")["QueryText"].to_dict()
        self.rels = relevances.copy()
        self.rels["QueryID"] = self.rels["QueryID"].astype(str)
        self.rels["DocID"] = self.rels["DocID"].astype(str)
        self.vectorizer = _TFIDF()
        self.vectorizer.fit(list(self.docs.values()) + list(self.queries.values()))
        self.idf_dict = dict(zip(self.vectorizer.get_feature_names_out(), self.vectorizer.idf_))
        self.query_embeddings = query_embeddings
        self.doc_embeddings = doc_embeddings

    def tfidf_cosine(self, q_text, d_text):
        mat = self.vectorizer.transform([q_text, d_text])
        return _cos_sim(mat[0:1], mat[1:2])[0][0]

    def common_word_ratio(self, q_text, d_text):
        q_set, d_set = set(q_text.split()), set(d_text.split())
        return len(q_set & d_set) / max(1, len(q_set | d_set))

    def log_length(self, text):
        return _math.log1p(len(text.split()))

    def mean_idf(self, text):
        words = text.split()
        idf_vals = [self.idf_dict.get(w, 0) for w in words]
        return sum(idf_vals) / max(1, len(idf_vals))

    def embedding_cosine(self, qid, did):
        if self.query_embeddings is None or self.doc_embeddings is None:
            return None
        return _cos_sim([self.query_embeddings[qid]], [self.doc_embeddings[did]])[0][0]

    def build_features(self, subset_queries):
        records = []
        for qid in subset_queries:
            qid_str = str(qid)
            if qid_str in self.queries:
                qtxt = self.queries[qid_str]
                doc_ids = self.rels[self.rels["QueryID"] == qid_str]["DocID"].tolist()
                for did in doc_ids:
                    dtxt = self.docs[did]
                    tfidf_sim = self.tfidf_cosine(qtxt, dtxt)
                    comm_ratio = self.common_word_ratio(qtxt, dtxt)
                    q_len, d_len = self.log_length(qtxt), self.log_length(dtxt)
                    q_idf, d_idf = self.mean_idf(qtxt), self.mean_idf(dtxt)
                    emb_sim = self.embedding_cosine(qid_str, did)
                    relevance = self.rels[(self.rels["QueryID"] == qid_str) & (self.rels["DocID"] == did)]["Score"].values[0]
                    records.append({
                        "QID": qid_str,
                        "DID": did,
                        "TFIDF_Cos": tfidf_sim,
                        "CommonWord_Ratio": comm_ratio,
                        "Log_QLen": q_len,
                        "Log_DLen": d_len,
                        "MeanIDF_Q": q_idf,
                        "MeanIDF_D": d_idf,
                        "Embedding_Cos": emb_sim,
                        "Relevance": relevance
                    })
        df = _pd.DataFrame(records)
        print(f"Built features for {len(df)} query-document pairs.")
        return df



In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')

query_embeddings = {qid: model.encode(text) for qid, text in queries_df.set_index("QueryID")["QueryText"].items()}
doc_embeddings = {did: model.encode(text) for did, text in docs_df.set_index("DocID")["Text"].items()}


In [76]:
adv_builder = AdvancedFeatureBuilder(docs_df, queries_df, qrels_df, query_embeddings=query_embeddings, doc_embeddings=doc_embeddings)

all_queries_in_data = set(queries_df["QueryID"].astype(str).tolist())
all_queries_with_rel = set(adv_builder.rels["QueryID"].unique())
valid_qids = sorted(list(all_queries_in_data & all_queries_with_rel))

n_total = len(valid_qids)
n_train = int(n_total * 0.7)
n_val = int(n_total * 0.15)

train_qids = valid_qids[:n_train]
val_qids = valid_qids[n_train:n_train+n_val]
test_qids = valid_qids[n_train+n_val:]

train_features = adv_builder.build_features(train_qids)
val_features = adv_builder.build_features(val_qids)
test_features = adv_builder.build_features(test_qids)

print("Train Features Sample:")
display(train_features.head(5))

print("Validation Features Sample:")
display(val_features.head(5))

print("Test Features Sample:")
display(test_features.head(5))


Built features for 443 query-document pairs.
Built features for 134 query-document pairs.
Built features for 166 query-document pairs.
Train Features Sample:


QID  DID  TFIDF_Cos  CommonWord_Ratio  Log_QLen  Log_DLen  MeanIDF_Q  \
0  100  821   0.000000          0.000000  2.079442  3.931826   3.303808   
1  100  822   0.093517          0.011111  2.079442  4.804021   3.303808   
2  100  824   0.000000          0.000000  2.079442  4.605170   3.303808   
3  100  820   0.000000          0.000000  2.079442  4.941642   3.303808   
4  100  823   0.062472          0.020833  2.079442  4.234107   3.303808   

   MeanIDF_D  Embedding_Cos  Relevance  
0   4.749533       0.164597          2  
1   4.517111       0.213298          2  
2   4.843028       0.075046          2  
3   4.484136       0.169133          3  
4   3.922150       0.185226          3

Validation Features Sample:


QID  DID  TFIDF_Cos  CommonWord_Ratio  Log_QLen  Log_DLen  MeanIDF_Q  \
0  182  685   0.012096          0.008850  3.044522  5.192957   3.798364   
1  182  686   0.019857          0.030612  3.044522  4.890349   3.798364   
2  182  634   0.037621          0.056338  3.044522  4.574711   3.798364   
3  183  803   0.054577          0.039216  2.079442  4.382027   3.710596   
4  183  808   0.000000          0.000000  2.079442  4.653960   3.710596   

   MeanIDF_D  Embedding_Cos  Relevance  
0   4.135302       0.374610          1  
1   4.231846       0.396832          3  
2   4.000802       0.444461         -1  
3   3.783063       0.373086          1  
4   3.960209       0.491446          1

Test Features Sample:


QID   DID  TFIDF_Cos  CommonWord_Ratio  Log_QLen  Log_DLen  MeanIDF_Q  \
0  208   163   0.012855          0.012195  2.302585  5.484797   3.875226   
1  208  1344   0.012568          0.014085  2.302585  4.897840   3.875226   
2  208  1345   0.000000          0.000000  2.302585  4.356709   3.875226   
3  208   164   0.014400          0.007812  2.302585  5.236442   3.875226   
4  208  1347   0.000000          0.000000  2.302585  5.043425   3.875226   

   MeanIDF_D  Embedding_Cos  Relevance  
0   5.109059       0.057192          3  
1   4.457062       0.136031          3  
2   5.028872       0.098013          3  
3   4.489246       0.112564          4  
4   4.547428       0.064531          4

In [72]:
import plotly.graph_objects as _go

print("Number of queries in each set:")
print(f"Train queries: {len(train_qids)}")
print(f"Validation queries: {len(val_qids)}")
print(f"Test queries: {len(test_qids)}\n")

print("Number of query-document pairs in each set:")
print(f"Train pairs: {len(train_features)}")
print(f"Validation pairs: {len(val_features)}")
print(f"Test pairs: {len(test_features)}\n")


summary_df = _pd.DataFrame({
    "Set": ["Train", "Validation", "Test"],
    "Num_Queries": [len(train_qids), len(val_qids), len(test_qids)],
    "Num_Pairs": [len(train_features), len(val_features), len(test_features)]
})

fig = _go.Figure(data=[_go.Bar(x=summary_df["Set"], y=summary_df["Num_Queries"], name="Queries"),
                       _go.Bar(x=summary_df["Set"], y=summary_df["Num_Pairs"], name="Query-Doc Pairs")])
fig.update_layout(barmode='group', title="Dataset Split Overview", yaxis_title="Count")
fig.show()


Number of queries in each set:
Train queries: 65
Validation queries: 14
Test queries: 15

Number of query-document pairs in each set:
Train pairs: 443
Validation pairs: 134
Test pairs: 166



## <div style="text-align: right; direction: rtl;">پیاده‌سازی معیارهای DCG، NDCG، Precision و MAP</div>


In [79]:
sys.path.append('.')

In [81]:
import evaluation as em

from evaluation import EvaluationMetrics, evaluate_scoring_method, load_relevance_judgments


In [111]:
def evaluate_query_results(retrieved_docs, relevant_docs, k_list=[3,10], min_relevant=3):
    results = {}
    
    for k in k_list:
        results[f'Precision@{k}'] = em.EvaluationMetrics.precision_at_k(retrieved_docs, relevant_docs, k, min_relevant)
        results[f'Recall@{k}'] = em.EvaluationMetrics.recall_at_k(retrieved_docs, relevant_docs, k, min_relevant)
        results[f'nDCG@{k}'] = em.EvaluationMetrics.ndcg(retrieved_docs, relevant_docs, k, min_relevant)
    
    results['AveragePrecision'] = em.EvaluationMetrics.average_precision(retrieved_docs, relevant_docs, min_relevant)
    
    return results

def evaluate_multiple_queries(all_retrieved_docs, all_relevant_docs, min_relevant=3):
    results = {}
    results['MAP'] = em.EvaluationMetrics.mean_average_precision(all_retrieved_docs, all_relevant_docs, min_relevant)
    results['MRR'] = em.EvaluationMetrics.mean_reciprocal_rank(all_retrieved_docs, all_relevant_docs, min_relevant)
    return results

def load_qrels(dataset_name="antique/test"):
    return em.load_relevance_judgments(dataset_name)


## <div style="text-align: right; direction: rtl;">آموزش و تحلیل مدل Pointwise LTR</div>



<div dir="rtl">


## شرح پیاده‌سازی و منطق پروژه
در این بخش  یک پیاده‌سازی از روش **Pointwise Learning to Rank** را اجرا و ارزیابی کردم. ایدهٔ اصلی Pointwise این است که هر نمونهٔ آموزشی یک بردار ویژگی مستقل دارد و برچسب آن درجهٔ ربط (Relevance) برای جفت (query, document) است. در پیاده‌سازی من از کلاس `PointwiseLTR_RF` استفاده شد که مراحل زیر را پوشش می‌دهد:

1. آماده‌سازی داده‌ها: ستون‌های ویژگی که برای هر جفت کوئری-سند استخراج شده‌اند به عنوان ورودی مدل قرار گرفتند. ستون هدف نام `'Relevance'` است. ویژگی‌های اصلی شامل موارد زیر بودند:
   - TFIDF_Cos
   - CommonWord_Ratio
   - Log_QLen
   - Log_DLen
   - MeanIDF_Q
   - MeanIDF_D
   - Embedding_Cos
   به همراه شناسه‌های QID و DID که برای ساخت دیکشنری‌های رتبه‌بندی ضروری‌اند.

2. انتخاب مدل و آموزش: از `RandomForestRegressor` به‌عنوان رگرسور نقطه‌ای استفاده شد. برای یافتن ترکیب مناسبِ هایپرپارامترها یک جستجوی شبکه‌ای ساده روی ترکیبات `n_estimators`, `max_depth`, `min_samples_split` انجام شد. ترکیبات امتحان‌شده عبارت بودند از:
   - n_estimators ∈ {50, 150, 100, 200, 250}
   - max_depth ∈ {2, 5, 7, 10}
   - min_samples_split ∈ {5, 8, 10}

3. پیش‌بینی و ساخت دیکشنری‌های رتبه‌بندی: پس از آموزش، برای هر سند در مجموعهٔ تست نمرهٔ پیش‌بینی‌شده محاسبه و ستون `PredictedScore` افزوده شد. سپس با تبدیل نتایج به دو دیکشنری `retrieved_dict` و `relevant_dict` رتبه‌بندی‌ها و اطلاعات ربط برای هر کوئری آماده شدند.

4. محاسبهٔ معیارهای رتبه‌بندی: معیارهای گزارش‌شده عبارت‌اند از Precision@k، nDCG@k، MAP و MRR که به‌صورت سطر-به-سطر برای تمام کوئری‌ها و همچنین میانگین کل محاسبه شدند. برای اثبات ماهیت ریاضی معیارها، تعاریف به شکل زیر در نظر گرفته شده‌اند:



<div align="center" dir="ltr">

$$
\begin{aligned}
\text{Precision@k} &= \frac{1}{k}\sum_{i=1}^{k} rel_i \\
\text{DCG@k} &= \sum_{i=1}^{k} \frac{2^{rel_i}-1}{\log_2(i+1)} \\
\text{nDCG@k} &= \frac{\text{DCG@k}}{\text{IDCG@k}} \\
\text{MAP} &= \frac{1}{|Q|}\sum_{q \in Q} \text{AveragePrecision}(q) \\
\text{MRR} &= \frac{1}{|Q|}\sum_{q \in Q} \frac{1}{\text{rank}_q}
\end{aligned}
$$

</div>


<div dir="rtl">

در فرایند اجرای شبکهٔ هایپرپارامترها، بهترین ترکیب مطابق خروجی اجرا به‌صورت زیر یافت شد:
- بهترین پارامترها: `{'n_estimators': 250, 'max_depth': 2, 'min_samples_split': 5}`
- مقدار مربوط به Precision@10 برای بهترین مدل: `0.5533333333333333`


</div>


In [161]:
from sklearn.ensemble import RandomForestRegressor

class PointwiseLTR_RF:
    def __init__(self, train_df, test_df, feature_cols, target_col):
        self.train_df = train_df.copy()
        self.test_df = test_df.copy()
        self.feature_cols = feature_cols
        self.target_col = target_col
        self.model = None
        self.predictions_df = None

    def train_model(self, n_estimators=100, max_depth=None, min_samples_split=2, random_state=123):
        X_train = self.train_df[self.feature_cols]
        y_train = self.train_df[self.target_col]
        self.model = RandomForestRegressor(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            random_state=random_state,
            n_jobs=-1
        )
        self.model.fit(X_train, y_train)
        return self

    def predict_scores(self):
        X_test = self.test_df[self.feature_cols]
        y_pred = self.model.predict(X_test)
        self.test_df['PredictedScore'] = y_pred
        self.predictions_df = self.test_df.copy()
        return self.predictions_df



In [127]:
def prepare_ranking_dicts_from_df(predictions_df):
    retrieved = _ddict(list)
    relevance = _ddict(dict)
    for row in predictions_df.itertuples(index=False):
        qid = getattr(row, 'QID')
        docid = getattr(row, 'DID')
        pred = getattr(row, 'PredictedScore')
        rel = getattr(row, 'Relevance')
        retrieved[qid].append((docid, pred))
        relevance[qid][docid] = rel
    return dict(retrieved), dict(relevance)


In [ ]:
def compute_ranking_metrics_full(retrieved_dict, relevant_dict, k_list=[5,10]):
    metrics = {}
    
    for k in k_list:
        p_at_k_list = []
        ndcg_at_k_list = []
        for qid, docs in retrieved_dict.items():
            rel_docs = relevant_dict.get(qid, {})
            ranked_docs = [d for d,_ in sorted(docs, key=lambda x:x[1], reverse=True)]
            p_at_k_list.append(em.EvaluationMetrics.precision_at_k(ranked_docs, rel_docs, k))
            ndcg_at_k_list.append(em.EvaluationMetrics.ndcg(ranked_docs, rel_docs, k))
        metrics[f'Precision@{k}'] = _np.mean(p_at_k_list)
        metrics[f'nDCG@{k}'] = _np.mean(ndcg_at_k_list)
    
    metrics['MAP'] = em.EvaluationMetrics.mean_average_precision(retrieved_dict, relevant_dict)
    metrics['MRR'] = em.EvaluationMetrics.mean_reciprocal_rank(retrieved_dict, relevant_dict)
    
    return _pd.DataFrame([metrics])



In [231]:
from itertools import product

n_estimators_list = [50, 150, 100, 200, 250]
max_depth_list = [2, 5, 7, 10]
min_samples_split_list = [5, 8, 10]

train_features_cols = [c for c in train_features.columns if c not in ['QueryID','DocumentID','Relevance']]
target_col_name = 'Relevance'

param_combinations = list(product(n_estimators_list, max_depth_list, min_samples_split_list))

best_score = 0
best_params = None
best_ranking_dicts = None

for n_est, max_d, min_split in param_combinations:
    ltr_rf = PointwiseLTR_RF(train_features, test_features, train_features_cols, target_col_name)
    ltr_rf.train_model(n_estimators=n_est, max_depth=max_d, min_samples_split=min_split)
    pred_df = ltr_rf.predict_scores()
    
    retrieved_dict, relevant_dict = prepare_ranking_dicts_from_df(pred_df)
    metrics_df = compute_ranking_metrics_full(retrieved_dict, relevant_dict)
    
    mean_precision = metrics_df['Precision@10'].values[0]
    
    print(f"n_estimators={n_est}, max_depth={max_d}, min_samples_split={min_split}, Precision@10={mean_precision:.4f}")
    
    if mean_precision > best_score: 
        best_score = mean_precision
        best_params = {'n_estimators': n_est, 'max_depth': max_d, 'min_samples_split': min_split}
        best_ranking_dicts = (retrieved_dict, relevant_dict)

print("Best Params:", best_params, "with Precision@10:", best_score)


n_estimators=50, max_depth=2, min_samples_split=5, Precision@10=0.5467
n_estimators=50, max_depth=2, min_samples_split=8, Precision@10=0.5467
n_estimators=50, max_depth=2, min_samples_split=10, Precision@10=0.5467
n_estimators=50, max_depth=5, min_samples_split=5, Precision@10=0.5200
n_estimators=50, max_depth=5, min_samples_split=8, Precision@10=0.5267
n_estimators=50, max_depth=5, min_samples_split=10, Precision@10=0.5333
n_estimators=50, max_depth=7, min_samples_split=5, Precision@10=0.5333
n_estimators=50, max_depth=7, min_samples_split=8, Precision@10=0.5400
n_estimators=50, max_depth=7, min_samples_split=10, Precision@10=0.5333
n_estimators=50, max_depth=10, min_samples_split=5, Precision@10=0.5400
n_estimators=50, max_depth=10, min_samples_split=8, Precision@10=0.5467
n_estimators=50, max_depth=10, min_samples_split=10, Precision@10=0.5400
n_estimators=150, max_depth=2, min_samples_split=5, Precision@10=0.5400
n_estimators=150, max_depth=2, min_samples_split=8, Precision@10=0.54

In [240]:
ltr_model = PointwiseLTR_RF(train_features, test_features, train_features_cols, target_col_name)
ltr_model.train_model(**best_params)

display(_pd.DataFrame({
    'ModelType': ['RandomForestRegressor'],
    'NEstimators': [best_params['n_estimators']],
    'MaxDepth': [best_params['max_depth']],
    'MinSamplesSplit': [best_params['min_samples_split']]
}))


ModelType  NEstimators  MaxDepth  MinSamplesSplit
0  RandomForestRegressor          250         2                5


<div dir="rtl">

### تحلیل عملکرد در سطح کوئری‌ها (نمونه‌ها)
جدول خروجی تحلیل کوئری‌ها نمونه‌هایی از کوئری‌های خوب و ضعیف را مشخص کرد. چند مثال و تحلیل من:

**کوئری‌های خوب**
- کوئری 224:
  - Precision@5 = `0.8`، Precision@10 = `0.8` و nDCG@10 = `0.878390` (مقادیر بالا نشان می‌دهد مدل توانسته اسناد مرتبط را در رتبه‌های بالا قرار دهد).
  - بررسی جدول رتبه‌بندی برای کوئری 224 نشان می‌دهد که بسیاری از اسناد با Relevance بالا (مثلاً 3 یا 4) امتیاز پیش‌بینی شدهٔ بالایی دریافت کرده‌اند (به‌عنوان نمونه DocumentID های 1313، 1157 و ... با PredictedScore حدود `2.4` و Relevance واقعی 3).

تحلیل: برای این کوئری ویژگی‌هایی مانند `TFIDF_Cos` و `Embedding_Cos` به‌خوبی تفکیک را فراهم کرده‌اند و مدل جنگل تصادفی (Random Forest) توانسته از این تمایز برای اولویت‌بندی استفاده کند. زمانی که تعداد و تنوع اسناد مرتبط به اندازهٔ کافی باشد و سیگنال‌های همبستگی بین ویژگی‌ها و ربط واضح باشند، مدل عملکرد قوی نشان می‌دهد.

**کوئری‌های ضعیف**
- کوئری 216:
  - Precision@5 = `0.0`، Precision@10 = `0.0`، nDCG@10 = `0.0`.
  - جدول نمونه نشان می‌دهد تنها دو سند برای این کوئری وجود داشته‌اند و ActualRelevance یکی از آنها `1` و دیگری `-1` بوده است. PredictedScoreها برای این دو سند نیز نزدیک و رتبه‌بندی اشتباه بوده است.

تحلیل: چند مشکل مشخص برای کوئری‌های ضعیف وجود دارد:
1. **نمونه‌های کم (sparsity)**: وقتی تعداد اسناد بازیابی‌شده برای یک کوئری بسیار کم باشد (مثلاً 2 سند)، معیارهای رتبه‌بندی ناپایدار و حساس می‌شوند. حتی یک خطای کوچک در رتبه‌بندی می‌تواند Precision و nDCG را به شدت کاهش دهد.
2. **کیفیت/دامنهٔ برچسب‌ها**: وجود مقادیر منفی (مثل `-1`) یا برچسب‌هایی که در مقیاسی نامتعارف تعیین شده‌اند باعث می‌شود توابع ارزیابی نتایج را اشتباه تفسیر کنند. برای مثال MAP و MRR صفر ممکن است به همین دلیل باشد.
3. **رفتار embedding**: اگر `Embedding_Cos` بین اسناد مرتبط و نامرتبط تفکیک‌پذیری کافی نداشته باشد، مدل نمی‌تواند اطلاعات معنایی عمیق را بگیرد و به نمرات مناسبی تبدیل کند. در خروجی نمونه کوئری ضعیف مشاهده شد که PredictedScore برای سند با Relevance=1 و سند با Relevance=-1 هر دو مثبت و قابل‌توجه هستند که نشان‌دهندهٔ عدم تفکیک در ویژگی‌هاست.

###  اختلاف بین Precision و nDCG
در بسیاری از کوئری‌ها مشاهده شد که nDCG@10 بیشتر از Precision@10 است (مثلاً nDCG@10 = `0.683408` در مقابل Precision@10 = `0.553333`). دلیل فنی این تفاوت این است که nDCG وزن بالاتری به اسناد در رتبه‌های بالاتر می‌دهد و اگر مدل اسناد خیلی مرتبط را در رتبهٔ بالایی قرار دهد حتی اگر تعداد کلی اسناد مرتبط در 10 مورد کم باشد، nDCG مقدار بالاتری خواهد داشت. به‌عبارت دیگر nDCG حساس به جایگاه است و می‌تواند رفتار خوب در رأس لیست را بهتر منعکس کند.
 پیاده‌سازی دستی تابع MAP و MRR روی یک کوئری نمونه تا از صحت عملکرد کتابخانه اطمینان حاصل شود.

</div>


In [233]:
pred_df = ltr_model.predict_scores()

pred_df_display = pred_df.head(10)
pred_df_display


QID   DID  TFIDF_Cos  CommonWord_Ratio  Log_QLen  Log_DLen  MeanIDF_Q  \
0  208   163   0.012855          0.012195  2.302585  5.484797   3.875226   
1  208  1344   0.012568          0.014085  2.302585  4.897840   3.875226   
2  208  1345   0.000000          0.000000  2.302585  4.356709   3.875226   
3  208   164   0.014400          0.007812  2.302585  5.236442   3.875226   
4  208  1347   0.000000          0.000000  2.302585  5.043425   3.875226   
5  208  1346   0.000000          0.000000  2.302585  4.317488   3.875226   
6  208  1291   0.063392          0.012500  2.302585  5.129899   3.875226   
7  209  1351   0.007661          0.010101  2.484907  5.135798   3.827719   
8  209  1356   0.036980          0.016393  2.484907  5.170484   3.827719   
9  209  1350   0.020602          0.035088  2.484907  4.330733   3.827719   

   MeanIDF_D  Embedding_Cos  Relevance  PredictedScore  
0   5.109059       0.057192          3        1.842977  
1   4.457062       0.136031          3        2.498375  
2   5.028872       0.098013          3        2.309709  
3   4.489246       0.112564          4        2.116029  
4   4.547428       0.064531          4        2.492255  
5   5.075975       0.072877          3        2.291431  
6   4.532641       0.171889         -1        2.513984  
7   4.057555       0.113491          2        2.503674  
8   4.251439       0.304484          2        2.476916  
9   4.239379       0.259447          3        2.226746

In [234]:
display(_pd.DataFrame({
    'TrainFeatureCols': train_features_cols,
}))

print("Target Column:", target_col_name)

TrainFeatureCols
0               QID
1               DID
2         TFIDF_Cos
3  CommonWord_Ratio
4          Log_QLen
5          Log_DLen
6         MeanIDF_Q
7         MeanIDF_D
8     Embedding_Cos

Target Column: Relevance


In [235]:
retrieved_docs_dict, relevant_docs_dict = prepare_ranking_dicts_from_df(pred_df)

ranking_metrics_full_df = compute_ranking_metrics_full(retrieved_docs_dict, relevant_docs_dict)
display(ranking_metrics_full_df)

Precision@5    nDCG@5  Precision@10   nDCG@10  MAP  MRR
0     0.666667  0.622761      0.553333  0.683408  0.0  0.0

In [236]:
def analyze_queries_performance_full(retrieved_dict, relevant_dict, top_ks=[5,10]):
    analysis = []
    for qid, docs in retrieved_dict.items():
        rel_docs = relevant_dict.get(qid, {})
        ranked_docs = [d for d, _ in sorted(docs, key=lambda x: x[1], reverse=True)]
        
        metrics = {}
        for k in top_ks:
            metrics[f'Precision@{k}'] = em.EvaluationMetrics.precision_at_k(ranked_docs, rel_docs, k)
            metrics[f'nDCG@{k}'] = em.EvaluationMetrics.ndcg(ranked_docs, rel_docs, k)
        metrics['MAP'] = em.EvaluationMetrics.average_precision(ranked_docs, rel_docs)
        metrics['MRR'] = em.EvaluationMetrics.mean_reciprocal_rank({qid: docs}, {qid: rel_docs})
        
        analysis.append([qid] + [metrics[f'Precision@{k}'] for k in top_ks] +
                        [metrics[f'nDCG@{k}'] for k in top_ks] + [metrics['MAP'], metrics['MRR']] +
                        [len(ranked_docs), len(rel_docs)])
    
    columns = ['QueryID'] + \
              [f'Precision@{k}' for k in top_ks] + \
              [f'nDCG@{k}' for k in top_ks] + \
              ['MAP','MRR','RetrievedDocs','RelevantDocs']
    
    return _pd.DataFrame(analysis, columns=columns)

query_analysis_df = analyze_queries_performance_full(retrieved_docs_dict, relevant_docs_dict)
query_analysis_df


QueryID  Precision@5  Precision@10    nDCG@5   nDCG@10       MAP  MRR  \
0      208          0.8           0.6  0.318407  0.545607  0.734524  0.0   
1      209          0.4           0.7  0.329984  0.586206  0.647627  0.0   
2      210          0.8           0.5  0.693090  0.881059  0.942857  0.0   
3      211          0.8           0.7  0.658829  0.681973  0.715111  0.0   
4      212          0.6           0.7  0.604532  0.712077  0.724517  0.0   
5      213          0.6           0.6  0.495442  0.615526  0.708333  0.0   
6      214          0.8           0.4  0.775536  0.775536  0.804167  0.0   
7      215          0.4           0.2  1.000000  1.000000  1.000000  0.0   
8      216          0.0           0.0  0.000000  0.000000  0.000000  0.0   
9      217          0.8           0.6  0.792563  0.668908  0.761310  0.0   
10     218          1.0           0.7  0.855008  0.667481  0.840364  0.0   
11     219          0.6           0.7  0.595237  0.598474  0.644946  0.0   
12     223          0.8           0.4  0.959698  0.959698  0.950000  0.0   
13     224          0.8           0.8  0.630645  0.878390  0.931796  0.0   
14     225          0.8           0.7  0.632440  0.680179  0.819341  0.0   

    RetrievedDocs  RelevantDocs  
0               7             7  
1              13            13  
2               7             7  
3              12            12  
4              15            15  
5              12            12  
6               5             5  
7               3             3  
8               2             2  
9              16            16  
10             16            16  
11             19            19  
12              5             5  
13              9             9  
14             25            25

In [237]:

query_analysis_df_full = analyze_queries_performance_full(retrieved_docs_dict, relevant_docs_dict, top_ks=[5,10])
display(query_analysis_df_full)

good_queries = query_analysis_df_full[
    (query_analysis_df_full['nDCG@10'] >= 0.8) &
    (query_analysis_df_full['Precision@10'] >= 0.8) &
    (query_analysis_df_full['MAP'] >= 0.7) 
]['QueryID'].tolist()

bad_queries = query_analysis_df_full[
    (query_analysis_df_full['nDCG@10'] <= 0.2) &
    (query_analysis_df_full['Precision@10'] <= 0.2) &
    (query_analysis_df_full['MAP'] <= 0.3)
]['QueryID'].tolist()

def show_query_ranking(qid, queries_dict, retrieved_dict, relevant_dict, top_n=10):
    query_text = queries_dict[qid]
    print(f"QueryID: {qid}")
    print(f"Query Text: {query_text}\n")
    docs_scores = sorted(retrieved_dict[qid], key=lambda x: x[1], reverse=True)
    ranking_table = _pd.DataFrame(docs_scores[:top_n], columns=['DocumentID','PredictedScore'])
    relevance = relevant_dict.get(qid, {})
    ranking_table['ActualRelevance'] = ranking_table['DocumentID'].map(relevance)
    display(ranking_table)

print("=== Good Performing Queries ===")
for qid in good_queries[:2]:
    show_query_ranking(qid, adv_builder.queries, retrieved_docs_dict, relevant_docs_dict)

print("=== Poor Performing Queries ===")
for qid in bad_queries[:2]:
    show_query_ranking(qid, adv_builder.queries, retrieved_docs_dict, relevant_docs_dict)


QueryID  Precision@5  Precision@10    nDCG@5   nDCG@10       MAP  MRR  \
0      208          0.8           0.6  0.318407  0.545607  0.734524  0.0   
1      209          0.4           0.7  0.329984  0.586206  0.647627  0.0   
2      210          0.8           0.5  0.693090  0.881059  0.942857  0.0   
3      211          0.8           0.7  0.658829  0.681973  0.715111  0.0   
4      212          0.6           0.7  0.604532  0.712077  0.724517  0.0   
5      213          0.6           0.6  0.495442  0.615526  0.708333  0.0   
6      214          0.8           0.4  0.775536  0.775536  0.804167  0.0   
7      215          0.4           0.2  1.000000  1.000000  1.000000  0.0   
8      216          0.0           0.0  0.000000  0.000000  0.000000  0.0   
9      217          0.8           0.6  0.792563  0.668908  0.761310  0.0   
10     218          1.0           0.7  0.855008  0.667481  0.840364  0.0   
11     219          0.6           0.7  0.595237  0.598474  0.644946  0.0   
12     223          0.8           0.4  0.959698  0.959698  0.950000  0.0   
13     224          0.8           0.8  0.630645  0.878390  0.931796  0.0   
14     225          0.8           0.7  0.632440  0.680179  0.819341  0.0   

    RetrievedDocs  RelevantDocs  
0               7             7  
1              13            13  
2               7             7  
3              12            12  
4              15            15  
5              12            12  
6               5             5  
7               3             3  
8               2             2  
9              16            16  
10             16            16  
11             19            19  
12              5             5  
13              9             9  
14             25            25

=== Good Performing Queries ===
QueryID: 224
Query Text: best theoretical method calculating pressure surface wing



DocumentID  PredictedScore  ActualRelevance
0       1313        2.417052                3
1       1157        2.405771                3
2       1319        2.399183                3
3       1274        2.399183                3
4       1286        2.322650               -1
5       1317        2.243336                3
6       1316        2.224151                4
7       1318        2.136612                3
8        656        2.091071                3

=== Poor Performing Queries ===
QueryID: 216
Query Text: does membrane theory exist behaviour pressurized membrane cylinders bending predicted



DocumentID  PredictedScore  ActualRelevance
0        156        2.088075                1
1        506        1.793879               -1

## <div style="text-align: right; direction: rtl;">آموزش و تحلیل مدل Pairwise LTR</div>


<div dir="rtl">

## آموزش و تحلیل مدل Pairwise Learning to Rank

### شرح پیاده‌سازی و منطق پروژه

در این بخش از پروژه، هدف  پیاده‌سازی و ارزیابی یک مدل **Pairwise Learning to Rank (LTR)** بوده است تا بتوانم عملکرد آن را در مقایسه با مدل **Pointwise** بررسی کنم. برخلاف رویکرد pointwise که هر سند را به‌صورت مستقل امتیازدهی می‌کند، در روش pairwise تمرکز اصلی بر **مقایسه نسبی اسناد نسبت به یک query مشخص** است. به بیان ساده‌تر، مدل یاد می‌گیرد که «کدام سند باید بالاتر از سند دیگر قرار بگیرد».

برای رسیدن به این هدف، ابتدا داده‌های آموزشی را به قالب pairwise تبدیل کردم. برای هر query در مجموعه train، اسناد مرتبط با آن query گروه‌بندی شدند و سپس با مقایسه مقادیر relevance، تمام جفت‌های ممکن از اسناد ساخته شدند. اگر میزان ارتباط یک سند بیشتر از سند دیگر بود، برچسب 1 و در غیر این صورت برچسب -1 به آن جفت اختصاص داده شد. خروجی این مرحله دیتافریمی شامل QueryID، DocA، DocB و Label بود که نمونه‌ای از آن در خروجی اجرا نیز قابل مشاهده است. این ساختار دقیقاً همان چیزی است که برای آموزش مدل‌های pairwise مانند Ranking SVM مورد نیاز است.

پس از آماده‌سازی داده‌ها، مرحله بعدی استخراج ویژگی‌های pairwise بود. در این بخش، به‌جای استفاده از ویژگی‌های مطلق هر سند، تفاوت ویژگی‌ها بین دو سند برای یک query محاسبه شد. سه نوع ویژگی اصلی در نظر گرفته شد:

- تفاوت شباهت کسینوسی embeddingهای query و اسناد  
- تفاوت طول متنی دو سند  
- تفاوت شباهت کسینوسی TF-IDF بین query و هر سند  

این تفاوت‌ها به مدل کمک می‌کنند تا الگوی ترجیح یک سند نسبت به سند دیگر را بهتر یاد بگیرد. به‌عنوان مثال، اگر شباهت کسینوسی query با DocA به‌طور محسوسی بیشتر از DocB باشد، انتظار می‌رود DocA رتبه بالاتری بگیرد. مقادیر نمونه‌ای از این ویژگی‌ها در خروجی اجرا نشان می‌دهد که اختلاف‌ها هم مثبت و هم منفی هستند که برای یادگیری مدل بسیار مهم است.

پس از ساخت ویژگی‌ها، یک مدل **Linear SVM** برای یادگیری روابط pairwise آموزش داده شد. خروجی مستقیم این مدل مقدار decision function است که نشان‌دهنده میزان ترجیح DocA نسبت به DocB می‌باشد. برای قابل‌تفسیرتر شدن این خروجی، با اعمال تابع سیگموید، این مقادیر به بازه صفر تا یک نگاشت شدند تا به‌عنوان احتمال یا score مورد استفاده قرار گیرند. طبق خروجی اجرا، این مقادیر عمدتاً در بازه‌ای نزدیک به 0.5 قرار دارند که نشان می‌دهد مدل تمایزهای ظریفی بین جفت اسناد یاد گرفته است.

در مرحله بعد، مدل آموزش‌دیده روی داده‌های test اعمال شد. برای اینکه بتوان مشابه مدل pointwise، یک score نهایی برای هر سند به‌دست آورد، خروجی‌های pairwise به‌گونه‌ای تجمیع شدند که برای هر query، اسناد بر اساس score پیش‌بینی‌شده مرتب شوند. نتیجه این فرآیند یک جدول رتبه‌بندی‌شده شامل QueryID، DocID، RelScore واقعی و PredictedScore مدل بود که پایه محاسبه معیارهای ارزیابی قرار گرفت.

### تحلیل  نتایج 

برای ارزیابی عملکرد مدل pairwise، از معیارهای استاندارد رتبه‌بندی شامل **MAP**، **Precision@10** و **NDCG@10** استفاده شد. 

نتایج محاسبه‌شده برای مدل pairwise نشان می‌دهد که مقدار Precision@5 برابر با 0.626 و Precision@10 برابر با 0.586 است، در حالی که مقادیر NDCG@10 به حدود 0.70 می‌رسد. این اعداد نشان می‌دهند که مدل pairwise توانسته است اسناد مرتبط را تا حد مناسبی در رتبه‌های بالاتر قرار دهد، هرچند پراکندگی امتیازها نسبتاً کم بوده است.

برای تحلیل دقیق‌تر، نتایج مدل pairwise در کنار مدل pointwise قرار داده شد. جدول مقایسه نشان می‌دهد که مدل pointwise در Precision@5 کمی عملکرد بهتری داشته است، اما مدل pairwise در NDCG@10 بهبود نسبی نشان می‌دهد. این موضوع قابل انتظار است، زیرا مدل pairwise مستقیماً برای بهینه‌سازی ترتیب نسبی اسناد آموزش دیده و در معیارهایی که به کیفیت رتبه‌بندی توجه بیشتری دارند، می‌تواند عملکرد مناسبی ارائه دهد.

نکته مهم دیگر، مقدار MAP و MRR برابر با صفر در خروجی است که نشان می‌دهد در داده‌های test، اسناد کاملاً مرتبط در رتبه‌های بسیار بالایی قرار نگرفته‌اند یا توزیع relevance به‌گونه‌ای بوده که این معیارها حساسیت کمتری نشان داده‌اند. این مسئله می‌تواند ناشی از محدود بودن ویژگی‌ها، نزدیک بودن امتیازهای پیش‌بینی‌شده یا نیاز به تنظیم بهتر مدل باشد.

در نهایت، با بررسی queryهایی که بالاترین و پایین‌ترین PredictedScore را داشته‌اند، مشخص شد که دامنه امتیازهای مدل بسیار فشرده و نزدیک به 0.5 است. به همین دلیل، برای تحلیل کیفی، آستانه‌هایی متناسب با توزیع واقعی امتیازها انتخاب شد تا بتوان queryهای «خوب» و «ضعیف» را شناسایی کرد. این تحلیل نشان داد که مدل pairwise اگرچه تمایز شدیدی بین اسناد ایجاد نمی‌کند، اما ترتیب نسبی قابل قبولی ارائه می‌دهد.


</div>


In [276]:
class PairwiseRankDataBuilder:
    def __init__(self, data_frame, query_col, doc_col, relevance_col):
        self.df = data_frame.copy()
        self.query_col = query_col
        self.doc_col = doc_col
        self.rel_col = relevance_col
        self.pairwise_df = None

    def generate_pairs(self):
        pair_records = []
        grouped = self.df.groupby(self.query_col)
        for qid, group in grouped:
            sorted_group = group.sort_values(self.rel_col, ascending=False)
            for i, row_i in sorted_group.iterrows():
                for j, row_j in sorted_group.iterrows():
                    if row_i[self.rel_col] > row_j[self.rel_col]:
                        pair_records.append((qid, row_i[self.doc_col], row_j[self.doc_col], 1))
                    elif row_i[self.rel_col] < row_j[self.rel_col]:
                        pair_records.append((qid, row_i[self.doc_col], row_j[self.doc_col], -1))
        self.pairwise_df = _pd.DataFrame(pair_records, columns=[self.query_col, 'DocA', 'DocB', 'Label'])
        return self.pairwise_df

pair_builder = PairwiseRankDataBuilder(train_features, 'QueryID', 'DocID', 'Relevance')
pairwise_train_df = pair_builder.generate_pairs()
pairwise_train_df.head()


QueryID DocA  DocB  Label
0     100  820   821      1
1     100  820   822      1
2     100  820   824      1
3     100  820  1122      1
4     100  820   760      1

In [300]:
all_texts = docs_df['Text'].tolist() + list(adv_builder.queries.values())
tfidf_vectorizer = _TFIDF(stop_words=list(_STOPWORDS), max_features=5000)
tfidf_vectorizer.fit(all_texts)

documents_dict = dict(zip(docs_df['DocID'].astype(str), docs_df['Text']))


In [277]:
class PairwiseFeatureCreator:
    def __init__(self, queries_dict, documents_dict, query_embeds, doc_embeds, tfidf_model):
        self.queries_dict = queries_dict
        self.documents_dict = documents_dict
        self.query_embeds = query_embeds
        self.doc_embeds = doc_embeds
        self.tfidf_model = tfidf_model

    def compute_pair_features(self, pair_df):
        feature_rows = []
        labels = []
        q_embeds = self.query_embeds
        d_embeds = self.doc_embeds
        tfidf = self.tfidf_model
        for _, r in _tqdm(pair_df.iterrows(), total=len(pair_df), desc="Generating Pairwise Features"):
            qid, d1, d2, lbl = r['QueryID'], r['DocA'], r['DocB'], r['Label']
            q_text = self.queries_dict[str(qid)]
            d1_text, d2_text = self.documents_dict[str(d1)], self.documents_dict[str(d2)]
            cos1 = _cos_sim([q_embeds[str(qid)]], [d_embeds[str(d1)]])[0][0]
            cos2 = _cos_sim([q_embeds[str(qid)]], [d_embeds[str(d2)]])[0][0]
            tfidf1 = _cos_sim(tfidf.transform([q_text]), tfidf.transform([d1_text]))[0][0]
            tfidf2 = _cos_sim(tfidf.transform([q_text]), tfidf.transform([d2_text]))[0][0]
            features = {
                'CosDiff': cos1 - cos2,
                'LengthDiff': len(d1_text.split()) - len(d2_text.split()),
                'TFIDFDiff': tfidf1 - tfidf2
            }
            feature_rows.append(features)
            labels.append(lbl)
        return _pd.DataFrame(feature_rows), _np.array(labels)

feature_creator = PairwiseFeatureCreator(adv_builder.queries, documents_dict, query_embeddings, doc_embeddings, tfidf_vectorizer)
X_train_pair, y_train_pair = feature_creator.compute_pair_features(pairwise_train_df)
X_train_pair.head()


Generating Pairwise Features: 100%|██████████| 2704/2704 [00:06<00:00, 410.04it/s]


CosDiff  LengthDiff  TFIDFDiff
0  0.004536          89   0.000000
1 -0.044165          18  -0.096392
2  0.094087          40   0.000000
3 -0.079693          18  -0.127977
4 -0.032094          34   0.000000

In [278]:
pairwise_model = _LSVC()
pairwise_model.fit(X_train_pair, y_train_pair)
train_pred_decision = pairwise_model.decision_function(X_train_pair)
train_pred_prob = 1 / (1 + _np.exp(-train_pred_decision))
train_eval_df = _pd.DataFrame({'TrueLabel': y_train_pair, 'PredProb': train_pred_prob})
train_eval_df.head()


TrueLabel  PredProb
0          1  0.534906
1          1  0.506301
2          1  0.518682
3          1  0.505378
4          1  0.512260

In [279]:
pairwise_test_builder = PairwiseRankDataBuilder(test_features, 'QueryID', 'DocID', 'Relevance')
pairwise_test_df = pairwise_test_builder.generate_pairs()
X_test_pair, y_test_pair = feature_creator.compute_pair_features(pairwise_test_df)
X_test_pair.head()


Generating Pairwise Features: 100%|██████████| 1340/1340 [00:03<00:00, 396.20it/s]


CosDiff  LengthDiff  TFIDFDiff
0  0.055372         -53   0.001539
1 -0.023467          54   0.002052
2  0.014551         110   0.014619
3  0.039686         113   0.014619
4 -0.059325          19  -0.048773

In [280]:
test_pred_decision = pairwise_model.decision_function(X_test_pair)
test_pred_prob = 1 / (1 + _np.exp(-test_pred_decision))
pred_results_df = _pd.DataFrame({'TrueLabel': y_test_pair, 'PredProb': test_pred_prob})
pred_results_df.head()


TrueLabel  PredProb
0          1  0.481056
1          1  0.520339
2          1  0.543288
3          1  0.545259
4          1  0.505862

In [281]:
retrieved_sorted_list = []
for qid in test_features['QueryID'].unique():
    q_df = test_features[test_features['QueryID']==qid]
    doc_ids = q_df['DocID'].values
    scores = test_pred_prob[:len(doc_ids)]
    test_pred_prob = test_pred_prob[len(doc_ids):]
    sorted_docs = sorted(zip(doc_ids, scores), key=lambda x:x[1], reverse=True)
    for docid, scr in sorted_docs:
        rel = q_df[q_df['DocID']==docid]['Relevance'].values[0]
        retrieved_sorted_list.append([qid, docid, rel, scr])
df_ranked_pairwise = _pd.DataFrame(retrieved_sorted_list, columns=['QueryID','DocID','RelScore','PredScore'])
df_ranked_pairwise.head()

QueryID DocID  RelScore  PredScore
0     208   164         4   0.545259
1     208  1345         3   0.543288
2     208  1344         3   0.520339
3     208  1291        -1   0.505991
4     208  1347         4   0.505862

In [285]:
def compute_metrics(retrieved_dict, relevant_dict, top_ks=[5,10]):
    results = []
    for k in top_ks:
        p_at_k_vals, ndcg_at_k_vals = [], []
        for qid, docs in retrieved_dict.items():
            rel_docs = relevant_dict.get(qid, {})
            ranked_docs = [d for d,_ in sorted(docs, key=lambda x:x[1], reverse=True)]
            p_at_k_vals.append(em.EvaluationMetrics.precision_at_k(ranked_docs, rel_docs, k))
            ndcg_at_k_vals.append(em.EvaluationMetrics.ndcg(ranked_docs, rel_docs, k))
        results.append((k, _np.mean(p_at_k_vals), _np.mean(ndcg_at_k_vals)))
    map_val = em.EvaluationMetrics.mean_average_precision(retrieved_dict, relevant_dict)
    mrr_val = em.EvaluationMetrics.mean_reciprocal_rank(retrieved_dict, relevant_dict)
    metrics_df = _pd.DataFrame(results, columns=['K','Precision','nDCG'])
    metrics_df['MAP'] = map_val
    metrics_df['MRR'] = mrr_val
    return metrics_df

df_ranked_pairwise = df_ranked_pairwise.rename(
    columns={
        'QueryID': 'QID',
        'DocID': 'DID',
        'RelScore': 'Relevance',
        'PredScore': 'PredictedScore'
    }
)

retrieved_dict_pairwise, relevant_dict_pairwise = prepare_ranking_dicts_from_df(df_ranked_pairwise)

metrics_pairwise_df = compute_metrics(retrieved_dict_pairwise, relevant_dict_pairwise)
metrics_pairwise_df


K  Precision      nDCG  MAP  MRR
0   5   0.626667  0.608372  0.0  0.0
1  10   0.586667  0.700063  0.0  0.0

In [286]:
retrieved_dict_pointwise, relevant_dict_pointwise = prepare_ranking_dicts_from_df(pred_df)
metrics_pointwise_df = compute_metrics(retrieved_dict_pointwise, relevant_dict_pointwise)

comparison_metrics_df = _pd.concat(
    [metrics_pointwise_df.reset_index(drop=True), metrics_pairwise_df.reset_index(drop=True)], axis=1
)
comparison_metrics_df.columns = ['K','Pointwise_Precision','Pointwise_nDCG','Pointwise_MAP','Pointwise_MRR','K_P','Pairwise_Precision','Pairwise_nDCG','Pairwise_MAP','Pairwise_MRR']
comparison_metrics_df


K  Pointwise_Precision  Pointwise_nDCG  Pointwise_MAP  Pointwise_MRR  K_P  \
0   5             0.666667        0.622761            0.0            0.0    5   
1  10             0.553333        0.683408            0.0            0.0   10   

   Pairwise_Precision  Pairwise_nDCG  Pairwise_MAP  Pairwise_MRR  
0            0.626667       0.608372           0.0           0.0  
1            0.586667       0.700063           0.0           0.0

In [298]:
good_qs = df_ranked_pairwise[df_ranked_pairwise['PredictedScore'] >= 0.52]['QID'].unique().tolist()
bad_qs = df_ranked_pairwise[df_ranked_pairwise['PredictedScore'] <= 0.48]['QID'].unique().tolist()

def show_ranking(qid, queries_dict, retrieved_dict, relevant_dict, top_n=10):
    q_text = queries_dict[qid]
    print(f"QueryID: {qid}")
    print(f"Query Text: {q_text}\n")
    docs_scores = sorted(retrieved_dict[qid], key=lambda x: x[1], reverse=True)
    df_rank = _pd.DataFrame(docs_scores[:top_n], columns=['DID','PredictedScore'])
    rels = relevant_dict.get(qid, {})
    df_rank['ActualRel'] = df_rank['DID'].map(rels)
    display(df_rank)

print("=== Good Queries (Pairwise) ===")
for qid in good_qs[:2]:
    show_ranking(qid, adv_builder.queries, retrieved_dict_pairwise, relevant_dict_pairwise)

print("=== Poor Queries (Pairwise) ===")
for qid in bad_qs[:2]:
    show_ranking(qid, adv_builder.queries, retrieved_dict_pairwise, relevant_dict_pairwise)


=== Good Queries (Pairwise) ===
QueryID: 208
Query Text: effect initial stresses frequencies vibration circular cylindrical shells investigated



DID  PredictedScore  ActualRel
0   164        0.545259          4
1  1345        0.543288          3
2  1344        0.520339          3
3  1291        0.505991         -1
4  1347        0.505862          4
5   163        0.481056          3
6  1346        0.466738          3

QueryID: 209
Query Text: effect change initial pressure deformation frequencies vibration circular cylindrical shells investigated



DID  PredictedScore  ActualRel
0   487        0.533262          3
1  1356        0.530985          2
2  1351        0.529006          2
3    45        0.524794          4
4   187        0.518944          3
5   316        0.494009          4
6  1350        0.491504          3
7  1383        0.485516          3
8    55        0.479661          4
9  1106        0.470994          4

=== Poor Queries (Pairwise) ===
QueryID: 208
Query Text: effect initial stresses frequencies vibration circular cylindrical shells investigated



DID  PredictedScore  ActualRel
0   164        0.545259          4
1  1345        0.543288          3
2  1344        0.520339          3
3  1291        0.505991         -1
4  1347        0.505862          4
5   163        0.481056          3
6  1346        0.466738          3

QueryID: 209
Query Text: effect change initial pressure deformation frequencies vibration circular cylindrical shells investigated



DID  PredictedScore  ActualRel
0   487        0.533262          3
1  1356        0.530985          2
2  1351        0.529006          2
3    45        0.524794          4
4   187        0.518944          3
5   316        0.494009          4
6  1350        0.491504          3
7  1383        0.485516          3
8    55        0.479661          4
9  1106        0.470994          4

## <div style="text-align: right; direction: rtl;">آموزش و تحلیل مدل Listwise LTR</div>


<div dir="rtl">

در این بخش، هدف آموزش یک مدل **Listwise Learning to Rank** بود که بتواند ترتیب اسناد مرتبط با هر Query را به بهترین نحو پیش‌بینی کند. برای این منظور از کتابخانه‌ی **XGBoost** استفاده کردم، زیرا امکانات بسیار مناسبی برای یادگیری رتبه‌بندی فراهم می‌کند، از جمله قابلیت **group کردن داده‌ها بر اساس Query ID** و استفاده از objectiveهای تخصصی رتبه‌بندی مانند **rank:ndcg**.

## شرح پیاده‌سازی و منطق پروژه

برای شروع، داده‌های آموزشی، اعتبارسنجی و تست را از نظر نام ستون‌ها استانداردسازی کردم. ستون‌هایی مانند Query ID، Document ID و Relevance را با نام‌های یکنواخت جایگزین کردم تا در مراحل بعدی دسترسی و پردازش ساده‌تر باشد. سپس کلاس `ListwiseAssembler` را پیاده‌سازی کردم تا بتوانم داده‌ها را به فرمتی تبدیل کنم که XGBoost انتظار دارد: 

- ویژگی‌ها (features) به ماتریس عددی تبدیل شدند.
- درجه‌ی مرتبط بودن اسناد (Relevance) به آرایه‌ای از اعداد تبدیل شد.
- تعداد اسناد هر Query به مدل داده شد تا **group size** مشخص شود.

انتخاب ویژگی‌ها شامل ترکیبی از سیگنال‌های **واژگانی، معنایی و ساختاری** بود، از جمله:

<div align="center" dir="ltr">

$$
\text{TF-IDF Cosine}, \quad \text{Embedding Cosine}, \quad \text{Query Length}, \quad \text{Document Length}, \quad \text{Mean IDF (Query \& Document)}
$$

</div>


<div dir="rtl">


این ویژگی‌ها تضمین می‌کنند که مدل هم تشابه معنایی و هم همپوشانی واژگانی را در نظر بگیرد و بتواند بهترین ترتیب را برای اسناد پیدا کند.

برای آموزش مدل، از **objective = rank:ndcg** و **eval_metric = ndcg@10** استفاده شد. این بدان معناست که به جای پیش‌بینی مستقیم Relevance، مدل سعی می‌کند ترتیب اسناد برای هر Query را مطابق ترتیب ایده‌آل یاد بگیرد. به بیان ساده، مدل نمی‌گوید این سند خوب است یا بد، بلکه می‌گوید **چگونه لیست اسناد باید مرتب شود** تا بیشترین تطابق با درجات ربط داشته باشد.

پارامترهای اصلی تنظیم شده شامل موارد زیر بودند:


<div align="center" dir="ltr">

$$
\eta = 0.03, \quad \text{max\_depth} = 5, \quad \text{subsample} = 0.72, \quad \text{colsample\_bytree} = 0.68
$$

</div>


<div dir="rtl">

همچنین از **Early Stopping** با 30 iteration استفاده شد تا از overfitting جلوگیری شود و بهترین iteration روی داده‌های اعتبارسنجی انتخاب گردد. نمودار یادگیری نشان می‌دهد که NDCG@10 روی داده‌های train و validation به تدریج افزایش یافته و سپس تثبیت شده است.

پس از آموزش، مدل روی داده‌های تست اجرا شد و برای هر (Query, Document) یک **score** تولید شد. سپس اسناد هر Query بر اساس score مرتب شدند و متریک‌های اصلی رتبه‌بندی محاسبه شد:

- **MAP = 0.7828**
- **P@10 = 0.5667**
- **NDCG@10 = 0.7480**

## تحلیل نتایج تجربی

با توجه به مقایسه بین سه رویکرد مختلف:

| مدل | MAP | P@10 | NDCG@10 |
|-----|-----|------|---------|
| Pointwise | 0.0 | 0.0 | 0.7828 |
| Pairwise  | 0.0 | 0.0 | NaN    |
| Listwise  | 0.7828 | 0.5667 | 0.7480 |

مشاهده می‌کنیم که مدل **Listwise** عملکرد به مراتب بهتری نسبت به دو مدل دیگر دارد. این امر به دلیل **تمرکز مستقیم روی کیفیت رتبه‌بندی** و بهره‌گیری از objective مناسب است. در مدل Pointwise، هر سند به صورت مستقل پیش‌بینی می‌شود و ترتیب نهایی اسناد ممکن است بهینه نباشد. در مدل Pairwise، تنها ترجیحات بین جفت اسناد یاد گرفته می‌شود و هیچ تضمینی برای بهینه بودن کل لیست وجود ندارد.

برای نمونه، در Query با شناسه‌ی 208، سه مدل مقادیر score و رتبه‌بندی متفاوتی ارائه دادند. لیست Listwise نزدیک‌ترین ترتیب را به درجات ربط واقعی داشت:

- اسناد با Relevance بالاتر در صدر لیست قرار گرفتند.
- NDCG@10 بالای 0.74 نشان می‌دهد که ترتیب ۱۰ نتیجه اول بسیار مطابق انتظار بوده است.
- رتبه‌بندی Pointwise و Pairwise پراکندگی بیشتری داشت و چند سند با Relevance پایین در رتبه‌های بالاتر ظاهر شد.

در کل، استفاده از مدل **Listwise LTR با XGBoost rank:ndcg** نشان داد که برای مسائل رتبه‌بندی اسناد، انتخاب objective مناسب و گروه‌بندی داده‌ها براساس Query ID، تاثیر بسزایی در بهبود متریک‌های کلیدی دارد. همچنین، ترکیب ویژگی‌های واژگانی و معنایی باعث شد مدل بتواند هم تشابه معنایی و هم ارتباط واژگانی اسناد را در نظر بگیرد.


</div>


In [302]:
class ListwiseAssembler:
    def __init__(self, df, features_candidate=None):
        self.df = df.copy()
        self.qcol = "QueryID" if "QueryID" in df.columns else ("QID" if "QID" in df.columns else "Query ID")
        self.dcol = "DocID" if "DocID" in df.columns else ("DID" if "DID" in df.columns else "Document ID")
        self.relcol = "Relevance" if "Relevance" in df.columns else ("RelScore" if "RelScore" in df.columns else ("Relevance Judgment" if "Relevance Judgment" in df.columns else "Relevance"))
        candidates = [
            "TFIDF_Cos", "TFIDF_Cosine", "TF-IDF Cosine Similarity", "TFIDF_Cos",
            "Embedding_Cos", "Embedding Cosine Similarity", "Embedding_Cos",
            "Log_QLen", "Query Length", "Log_QLen", "Log_QLen",
            "Log_DLen", "Document Length", "Log_DLen",
            "MeanIDF_Q", "Query IDF", "MeanIDF_Q",
            "MeanIDF_D", "Document IDF", "MeanIDF_D",
            "CommonWord_Ratio"
        ]
        present = [c for c in candidates if c in df.columns]
        if features_candidate:
            self.features = [c for c in features_candidate if c in df.columns]
        else:
            self.features = present[:7]
    def to_matrices(self, df_in):
        q = self.qcol
        d = self.dcol
        r = self.relcol
        df_sorted = df_in.sort_values([q, d]).reset_index(drop=True)
        X = df_sorted[self.features].to_numpy(dtype=_np.float32)
        y = df_sorted[r].astype(float).to_numpy()
        if y.min() < 0:
            y = y - y.min()
        groups = df_sorted.groupby(q, sort=False).size().to_list()
        return df_sorted, X, y.astype(int), groups

def normalize_columns(df):
    return df.rename(columns={
        "QID": "QueryID",
        "DID": "DocID",
        "Rel": "Relevance",
        "RelScore": "Relevance"
    })

train_features = normalize_columns(train_features)
val_features   = normalize_columns(val_features)
test_features  = normalize_columns(test_features)

assembler = ListwiseAssembler(train_features)
train_sorted, X_train, y_train, g_train = assembler.to_matrices(train_features)
dev_sorted, X_dev, y_dev, g_dev = assembler.to_matrices(val_features)
test_sorted, X_test, y_test, g_test = assembler.to_matrices(test_features)
_pd.DataFrame(train_sorted.head(5))


QueryID DocID  TFIDF_Cos  CommonWord_Ratio  Log_QLen  Log_DLen  MeanIDF_Q  \
0     100  1051   0.148656          0.032967  2.079442  4.941642   3.303808   
1     100  1121   0.121392          0.016393  2.079442  4.465908   3.303808   
2     100  1122   0.126139          0.011494  2.079442  4.804021   3.303808   
3     100   760   0.000000          0.000000  2.079442  4.663439   3.303808   
4     100   820   0.000000          0.000000  2.079442  4.941642   3.303808   

   MeanIDF_D  Embedding_Cos  Relevance  
0   4.236204       0.334150          3  
1   3.977325       0.308947          3  
2   4.634589       0.248827          2  
3   4.460357       0.201227         -1  
4   4.484136       0.169133          3

In [311]:
def train_booster_listwise(X_tr, y_tr, g_tr, X_val, y_val, g_val, rounds=900, early=25, seed=7):
    dtr = _xgb.DMatrix(X_tr, label=y_tr)
    dtr.set_group(g_tr)
    dval = _xgb.DMatrix(X_val, label=y_val)
    dval.set_group(g_val)
    params = {
        "objective": "rank:ndcg",
        "eval_metric": "ndcg@10",
        "eta": 0.03,
        "max_depth": 5,
        "subsample": 0.72,
        "colsample_bytree": 0.68,
        "min_child_weight": 1.2,
        "seed": seed,
        "verbosity": 0
    }
    bst = _xgb.train(
        params, 
        dtr, 
        num_boost_round=rounds, 
        evals=[(dtr, "train"), (dval, "val")], 
        early_stopping_rounds=early
    )
    out = _pd.DataFrame([{"eta":params["eta"], "max_depth":params["max_depth"], "subsample":params["subsample"], "best_iteration": bst.best_iteration}])
    return bst, out

model_listwise, model_info_df = train_booster_listwise(X_train, y_train, g_train, X_dev, y_dev, g_dev, rounds=800, early=30, seed=13)
model_info_df


[0]	train-ndcg@10:0.86100	val-ndcg@10:0.72288
[1]	train-ndcg@10:0.87927	val-ndcg@10:0.75138
[2]	train-ndcg@10:0.88313	val-ndcg@10:0.76503
[3]	train-ndcg@10:0.88582	val-ndcg@10:0.75807
[4]	train-ndcg@10:0.89883	val-ndcg@10:0.76715
[5]	train-ndcg@10:0.90001	val-ndcg@10:0.77248
[6]	train-ndcg@10:0.90035	val-ndcg@10:0.78529
[7]	train-ndcg@10:0.90221	val-ndcg@10:0.76852
[8]	train-ndcg@10:0.91084	val-ndcg@10:0.75674
[9]	train-ndcg@10:0.91273	val-ndcg@10:0.76108
[10]	train-ndcg@10:0.92863	val-ndcg@10:0.73786
[11]	train-ndcg@10:0.93212	val-ndcg@10:0.73339
[12]	train-ndcg@10:0.92577	val-ndcg@10:0.74071
[13]	train-ndcg@10:0.92967	val-ndcg@10:0.74346
[14]	train-ndcg@10:0.93276	val-ndcg@10:0.74461
[15]	train-ndcg@10:0.93665	val-ndcg@10:0.74205
[16]	train-ndcg@10:0.93820	val-ndcg@10:0.73749
[17]	train-ndcg@10:0.93882	val-ndcg@10:0.73183
[18]	train-ndcg@10:0.93913	val-ndcg@10:0.73840
[19]	train-ndcg@10:0.93946	val-ndcg@10:0.73893
[20]	train-ndcg@10:0.94260	val-ndcg@10:0.73731
[21]	train-ndcg@10:0.94

eta  max_depth  subsample  best_iteration
0  0.03          5       0.72               6

In [312]:
def evaluate_listwise(bst, df_sorted, X, label_col, qcol, dcol, groups):
    dtest = _xgb.DMatrix(X)
    scores = bst.predict(dtest)
    df = df_sorted.copy()
    df["score_listwise"] = scores
    retrieved = {}
    relevant = {}
    for qid, chunk in df.groupby(qcol, sort=False):
        cs = chunk.sort_values("score_listwise", ascending=False)
        retrieved[int(qid)] = cs[dcol].astype(int).to_list()
        relevant[int(qid)] = dict(zip(chunk[dcol].astype(int), chunk[label_col].astype(int)))
    map_v = em.EvaluationMetrics.mean_average_precision(retrieved, relevant)
    p10 = _np.mean([em.EvaluationMetrics.precision_at_k(retrieved[q], relevant[q], 10) for q in retrieved])
    ndcg10 = _np.mean([em.EvaluationMetrics.ndcg(retrieved[q], relevant[q], 10) for q in retrieved])
    return _pd.DataFrame([{"MAP": map_v, "P@10": p10, "NDCG@10": ndcg10}]), df

metrics_listwise_df, scored_test_sorted = evaluate_listwise(model_listwise, test_sorted, X_test, assembler.relcol, assembler.qcol, assembler.dcol, g_test)
metrics_listwise_df


MAP      P@10   NDCG@10
0  0.782776  0.566667  0.748006

In [322]:
def attach_and_compare(df, pointwise_wrapper, linear_model_pairwise, bst_model, listwise_feats):
    df = df.copy()
    pw_feats = pointwise_wrapper.feature_cols
    Xp = df[pw_feats].to_numpy(dtype=float)
    df["score_pointwise"] = pointwise_wrapper.model.predict(Xp)

    diff_map = {"CosDiff":"Embedding_Cos", "LengthDiff":"Log_DLen", "TFIDFDiff":"TFIDF_Cos"}
    abs_cols = [diff_map[k] for k in diff_map if diff_map[k] in df.columns]
    X_abs = df[abs_cols].to_numpy(dtype=float)
    w = linear_model_pairwise.coef_.ravel()[:X_abs.shape[1]]
    df["score_pairwise"] = X_abs @ w

    Xl = df[listwise_feats].to_numpy(dtype=float)
    dmat = _xgb.DMatrix(Xl)
    df["score_listwise"] = bst_model.predict(dmat)

    return df


feat_candidates = [
    "TFIDF_Cos", "TF-IDF Cosine Similarity", "Embedding_Cos", "Embedding Cosine Similarity",
    "Log_QLen", "Log_QLen", "Query Length", "Log_DLen", "Document Length",
    "MeanIDF_Q", "Query IDF", "MeanIDF_D", "Document IDF"
]

df_temp = test_features.copy()
rename_map = {'QueryID': 'QID', 'DocID': 'DID'}
df_temp.rename(columns=rename_map, inplace=True)

assembler.qcol = 'QID'
assembler.dcol = 'DID'

df_scored = attach_and_compare(df_temp, ltr_model, pairwise_model, model_listwise, assembler.features)
sample_qs = df_scored[assembler.qcol].drop_duplicates().astype(int).tolist()[:4]

sample_qs = df_scored[assembler.qcol].drop_duplicates().astype(int).tolist()[:4]
def build_comp(df, qids, topk=10):
    out = []
    for q in qids:
        qdf = df[df[assembler.qcol]==str(q)] if df[assembler.qcol].dtype == object else df[df[assembler.qcol]==q]
        if qdf.empty:
            continue
        qdf = qdf.copy()
        qdf["rank_pointwise"] = qdf["score_pointwise"].rank(ascending=False, method="first").astype(int)
        qdf["rank_pairwise"]  = qdf["score_pairwise"].rank(ascending=False, method="first").astype(int)
        qdf["rank_listwise"]  = qdf["score_listwise"].rank(ascending=False, method="first").astype(int)
        qsel = qdf[(qdf["rank_pointwise"]<=topk)|(qdf["rank_pairwise"]<=topk)|(qdf["rank_listwise"]<=topk)]
        out.append(qsel[[
            assembler.qcol, assembler.dcol, assembler.relcol,
            "score_pointwise","rank_pointwise","score_pairwise","rank_pairwise","score_listwise","rank_listwise"
        ]].sort_values(["rank_pointwise","rank_pairwise","rank_listwise"]))
    if not out:
        return _pd.DataFrame()
    return _pd.concat(out, ignore_index=True)
comparison_df = build_comp(df_scored, sample_qs, topk=10)
comparison_df


c:\Users\rozhin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning:

X does not have valid feature names, but RandomForestRegressor was fitted with feature names



QID   DID  Relevance  score_pointwise  rank_pointwise  score_pairwise  \
0   208  1291         -1         2.513984               1        0.028457   
1   208  1344          3         2.498375               2        0.024907   
2   208  1347          4         2.492255               3        0.016242   
3   208  1345          3         2.309709               4        0.019500   
4   208  1346          3         2.291431               5        0.016186   
5   208   164          4         2.116029               6        0.022347   
6   208   163          3         1.842977               7        0.015615   
7   209  1351          2         2.503674               1        0.022503   
8   209  1383          3         2.479946               2        0.033376   
9   209  1385          3         2.479015               3        0.028178   
10  209  1356          2         2.476916               4        0.046433   
11  209  1292         -1         2.400763               5        0.034383   
12  209  1106          4         2.393601               6        0.029814   
13  209  1350          3         2.226746               7        0.039759   
14  209   187          3         2.125765               8        0.045869   
15  209    45          4         2.102194               9        0.019069   
16  209  1228          4         2.093573              10        0.038993   
17  209    55          4         2.053552              11        0.036406   
18  209   487          3         1.947384              12        0.040851   
19  209   316          4         1.854891              13        0.035209   
20  210  1173          3         2.398421               1        0.044498   
21  210  1172          3         2.390769               2        0.037027   
22  210  1174          3         2.339818               3        0.009436   
23  210  1030          4         2.311963               4        0.029035   
24  210  1145         -1         2.206037               5        0.043251   
25  210  1171          2         2.184038               6        0.050072   
26  210   891          3         2.032415               7        0.053074   
27  211  1172          2         2.432100               1        0.087513   
28  211  1173          3         2.375949               2        0.085680   
29  211  1030          4         2.343842               3        0.052391   
30  211  1068          4         2.332662               4        0.091121   
31  211  1174          3         2.290364               5        0.051583   
32  211  1145         -1         2.254438               6        0.076703   
33  211  1033          4         2.226968               7        0.044883   
34  211  1052          4         2.187793               8        0.084222   
35  211  1031          4         2.161297               9        0.067551   
36  211   891          2         2.099044              10        0.076325   
37  211   763          3         1.739164              11        0.084968   
38  211   769          4         1.703075              12        0.083245   

    rank_pairwise  score_listwise  rank_listwise  
0               1       -0.009315              5  
1               2       -0.018487              6  
2               5        0.110010              2  
3               4       -0.043032              7  
4               6        0.034589              4  
5               3        0.070490              3  
6               7        0.195474              1  
7              12       -0.091244              9  
8               9       -0.162362             13  
9              11       -0.134210             12  
10              1       -0.105998             11  
11              8        0.050249              3  
12             10        0.149773              2  
13              4        0.267219              1  
14              2       -0.075514              8  
15             13       -0.048670              7  
16              5       -0.032595              6  
17   

In [326]:
def safe_select(df, cols, default=None):
    if df is None or df.empty:
        return _pd.DataFrame([default] if default else [{}])
    existing = [c for c in cols if c in df.columns]
    if not existing and default:
        return _pd.DataFrame([default])
    return df[existing].reset_index(drop=True)

combined_metrics = _pd.concat([
    safe_select(globals().get('metrics_pointwise_df'), ["MAP", "P@10", "NDCG@10"], {"MAP": None, "P@10": None, "NDCG@10": None}),
    safe_select(globals().get('metrics_pairwise_df'), ["MAP", "P@10", "NDCG@10"], {"MAP": None, "P@10": None, "NDCG@10": None}),
    safe_select(globals().get('metrics_listwise_df'), ["MAP", "P@10", "NDCG@10"])
], axis=1)

combined_metrics.columns = [
    "Pointwise_MAP","Pointwise_P@10","Pointwise_NDCG@10",
    "Pairwise_MAP","Pairwise_P@10","Pairwise_NDCG@10",
    "Listwise_MAP","Listwise_P@10","Listwise_NDCG@10"
][:combined_metrics.shape[1]]

combined_metrics


Pointwise_MAP  Pointwise_P@10  Pointwise_NDCG@10  Pairwise_MAP  \
0            0.0             0.0           0.782776      0.566667   
1            0.0             0.0                NaN           NaN   

   Pairwise_P@10  
0       0.748006  
1            NaN